### ISSUE TITLE
Create a toggle for ELK stack

### ISSUE THREAD

**Issue by originalname51** [US-CBP/GTAS#1007]
The ELK stack is a heavy-weight addition to GTAS. It is not technically needed for core functionality and therefore should have a toggle so GTAS can be run on hardware that is less robust.

AC1: Create a toggle that allows an administrator to turn on or off elk stack via a server restart. Turn off by default.
AC2: When the toggle is off change the homepage of GTAS from dashboard to flight.

**Comment by tsegay** [comment]
Elastic search and logstash will be needed for core functionality of gtas for right now. The passenger search form is backed by elastic search. But Kibana is optional, #1041 will address the kibana toggle.

Once I update the backend of the passengers search form to interchangeably search elastic search and mariadb , I will add one toggle for all ELK stack.
