### ISSUE TITLE
mvn hibernate:drop

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#1065]
gets stuck on flightpax . This is on the bag feature branch

**Comment by tsegay** [comment]
This is related to having a wrong character set on the database. The database has to be created with the correct character set setting before running `hibernate:create`.

`CREATE DATABASE IF NOT EXISTS gtas CHARACTER SET utf8 COLLATE utf8_general_ci;`

**Comment by originalname51** [comment]
validated on docker mariadb 10.
