### ISSUE TITLE
Test User Roles

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#1106]
- [ ] create users that have various role combinations assigned
- [ ] test ability to access pages associated with the roles
- [ ] test ability to access pages using known URLs for pages that should be inaccessible
- [ ] test ability to perform actions associated with role (i.e. manage queries, should be able to create, remove, update, etc.)

**Comment by originalname51** [comment]
Blocked by #1116 - 1116 redesigns user rules making this ticket ineffective until 1116 is done.

**Comment by sylbakar** [comment]
I tested this ticket and it did not meet accepted criteria  and opened a ticket #1816.
