### ISSUE TITLE
Roles preauthorization (work package)

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#1116]
- [ ] #1118 update the landing page to the modified Flights view
- [ ] #1119 remove View Flights and Passengers Role

**Comment by tjwdev** [comment]
These are for tracking additional components of this ticket at large:

[ ] Add Kibana Role (Design what this entails)
[ ] Fix front end display issues with actionable buttons being available when roles dictate they aren't (Two part process; Quick in the meantime, proper fix after)
