### ISSUE TITLE
Data Generator | rolling data into SAT

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#112]
Please set up data generator to constantly load new data each day.
- pick a reasonable number of flights
- pick a few different airports
- keep a consistent schedule if possible

**Comment by svempati2006** [comment]
Completed and uploaded the daily scheduler job to generate PNR and Apis
data on a daily basis and also when needed at an interval.Code uploaded to
google drive and shared with Maneesh.


Thank you,
Srinivasarao Vempati.

*Capital Infotech Inc.*

*41969 Ural Dr.*

*STONE RIDGE.*

*VA-20105.*
*Ph:703-340-0906.*
