### ISSUE TITLE
Upgrade ELK stack and add https.

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#1128]
Upgrade ELK stack and add https.

**Comment by originalname51** [comment]
Migrate ELK stack to new HTTPS version.

**Comment by originalname51** [comment]
Upgrade ELK stack and add https.

**Comment by tsegay** [comment]
- [ ] Enable TLS for Elasticsearch on the master node  (currently elastic search is running on a single node type.

- [ ] Enable TLS for Kibana

- [ ]  Enable TLS for Logstash
