### ISSUE TITLE
fuzzy watchlist monitoring & tuning

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#1138]
- [x] monitor volume and accuracy of fuzzy watchlist matches
- [x] propose ideas for tuning the hit frequency down to a manageable volume if required
- [ ] implement changes if required

**Comment by originalname51** [comment]
~4 - ~6.5 passengers / second processed per thread on fuzzy matching.

**Comment by originalname51** [comment]
Thread count caps at 7- any more and performance degrades.

**Comment by originalname51** [comment]
Fuzzy match is not matching on anything except exact first name / last name matches with slightly different dob. Relaxation of fields might be required.

**Comment by originalname51** [comment]
Potential changes to how data is passed in to algorithm identified; un-needed database calls identified; implementation being looked at.
