### ISSUE TITLE
Case countdown timer is wrong for outbound flights

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#1155]

**Comment by originalname51** [comment]
Server needs to be updated from UTC to correct timezone.

**Comment by lnpeng** [comment]
There is one hour difference on case countdown timer for outbound flights. 

I recorded Flights screen at 06/05/2019 2:02PM EST where Flight UA0804's ETA is 06/08/2019 14:40. And I recorded Cases screen at 06/05/2019 2:03PM EST where case countdown timer for the flight is 3d1h36m.

It should be 3d0h36m if Flight ETA's timezone is EST, right? If Flight ETA is in Central time zone, the countdown timer is correct.

**Comment by lnpeng** [comment]
I verified four inbound flights and one outbound flight in the test environment. Their case countdown timer works as expected.
