### ISSUE TITLE
Flights View | Partial Hit badges disappear

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#1165]
They were displayed for some time, now they seem to have disappeared. To recreate, generate a partial hit and notice the hit badge counter. A few minutes later, it is no longer displayed

**Comment by lnpeng** [comment]
I added passenger list to watch list, which generates eight partial hits for messages in the test environment. Verified that the hit badge counter displays 8 as expected in Flights view and there is a light red flag for each partial hit in Passengers view. The hit badge counter and light red flags no longer disappear.
