### ISSUE TITLE
Tools->Admin->Code Editor | Add new code doesn't work

### ISSUE THREAD

**Issue by lnpeng** [US-CBP/GTAS#1168]
Steps to reproduce:

  1.  go to Tools->Admin->Code Editor
  2.  go to Carrier Codes, Country Codes, or Airport Codes
  3.  click on "Add" new code
  4.  input ISO2 = AF, ISO3 = AFG, ISO Numeric = 004, Name = Afghanistan as a country code
  5.  click on "Save"
  6.  see DOM error in console window

Browser type: firefox

**Comment by gtasautumn** [comment]
Same as #1169, closing it.
