### ISSUE TITLE
Manage Timezones

### ISSUE THREAD

**Issue by originalname51** [US-CBP/GTAS#1174]
AC1: Convert time to UTC in database
AC2: Store any values coming in that are not UTC in their own column/table (keep UTC conversion)
AC3: Front end changes will be in local time of the airport (e.g. if GTAS is loaded in EST timezone all flights are EST).

**Comment by originalname51** [comment]
Flight leg highlighting might need to be tweaked.

**Comment by originalname51** [comment]
No tweaks required - highlighting is done on origin/dest.

**Comment by dje04001** [comment]
Passenger Details > PNR > Itinerary table, ETA is off by 6 hours on a flight from AMS>IAD

**Comment by dje04001** [comment]
Looks good now with the latest fixes.
