### ISSUE TITLE
Toggle Rule Runner

### ISSUE THREAD

**Issue by tsegay** [US-CBP/GTAS#1183]
This is useful when GTAS needs only to parse and load messages into the database.

**Comment by originalname51** [comment]
The place the toggle could go could be RuleRunnerScheduler

**Comment by originalname51** [comment]
Until we get the https://github.com/US-CBP/GTAS/issues/1151 issue completed the property will probably need to live under application_configuration in the database.

**Comment by originalname51** [comment]
Issue #1151 has been completed.

**Comment by originalname51** [comment]
validated through both modifying application.properties and default.application.properties. Works as intended.
