### ISSUE TITLE
Neo4j Back End api (work package)

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#1198]

**Comment by originalname51** [comment]
I will modify the Neo4J client(which uses the driver as a backbone), moving some of the specific rule implementation up to the graph rule service impl, and then use the neo4j client as a backbone in a new service for the webapp.

**Comment by originalname51** [comment]
After a design discussion with @TeddyTesfaye and @gtasautumn the path forward has changed to use a library that has the JavaScript neo4j driver as a base making the back end api work package unneeded for development.
