### ISSUE TITLE
Analysis of Double Metaphone / Jaro Winkler Distance & Other

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#1199]
Timeboxed for 2 days

**Comment by originalname51** [comment]
To analyze any enhancements that can be gained I will first state the fuzzy matching algorithm we use and the issue we are attempting to solve. It skips over some implementation details and requirements but is the core logic around our fuzzy matching.

1. Iterate over each passenger.
2. Each passenger iterates over the entire passenger watchlist (I'll call it listPerson).
    3. If the passenger is within a configurable(default is 3) years of the listPerson then proceed.
        4. If the passenger has the same double metaphone signature as listPerson name and scores within a configurable (default 95%) threshold by Jaro Winkler of listPerson's name then consider the passenger fuzzy matched. Otherwise proceed.
       5. If the passenger has the exact same birthday as listPassenger and passes the JaroWinkler threshhold consider the passenger fuzzy matched. Otherwise proceed.
END
  

Currently this logic is only reliably hitting on passengers who are an exact name match and within the birthdate-date threshhold of a watchlist member.

**Comment by originalname51** [comment]
Immediate thought is double metaphone and jarowinkler should not be linked. Given they measure a match in two different ways I think they should be separated in how they match.

**Comment by originalname51** [comment]
Currently we perform the Jaro Winkler algorithm on a full name. 

Jaro Winkler is a distance based text-matching algorithm which means passengers who share a long first name or last name and a different first or last name will still score highly on Jaro Winkler.

For example: Johnathan Smith and Johnathan Jones will score a 89.33 under Jaro Winkler when the input is the full name.

When Johnathan Smith and Johnathan Jones have each name run through Jaro Winkler and then averaged the result is 50. (Johnathan / Johnathan = 1, Jones/Smith = 0,  (1 + 0) / 2 = .50).

An easy enhancement that would allow us to give more weight to Jaro Winkler would be to stop analyzing the full name and instead analyze each component of a name seperately. As a bonus we could run the algorithm two more times to handle the case of the first name and last name getting flipped.

**Comment by originalname51** [comment]
In order to open the door to feedback on hit quality we should add a yes/no validity button to the pax watchlist link. This will replace the front end with a button.

**Comment by originalname51** [comment]
There should be a configurable toggle for creation of cases. That way if the fuzzy matching is too fuzzy we will not flood gtas with un-needed cases.

**Comment by originalname51** [comment]
To respect the timeboxing I've listed overall thoughts below

1. Focus on Jaro Winkler for passengers with typo's first by updating how we use Jaro Winkler and separating double metaphone. Perhaps limiting double metaphone to exact birthday match to keep it relevant.

2. Have a quality button on the front end to start capturing how close the hits are. This will start collecting data we can use to get better results, potentially through an algorithm using machine learning.

3.  Set up a toggle that will not make cases on fuzzy hits. This will help if the hit count gets too high, or if places want to configre away from fuzzy matching in favor of exact criteria matching.
