### ISSUE TITLE
Case View Enhancement

### ISSUE THREAD

**Issue by tjwdev** [US-CBP/GTAS#1220]
References Workspace epic #1217 and #1218

This ticket is to cover the future enhancement of the cases view under the new passenger detail tab. This ticket will allow for either distinct views, panels, or features according to the new cases view. This will include things like:
-Attachments

**Comment by originalname51** [comment]
Need a wireframe- here is the information we have on cases that we need to display

Data in a Case:

1. Case Hits
2. Case Hit Comments
3. Case Hit Comment Attachments
4. Case Hit Validation
5. Case Hit Disposition
6. Case general comments
7. Case Disposition
8. Promote to 1 day option
9. Ability to close case

**Comment by originalname51** [comment]
This is being re-worked as an overhaul and workflow - pulling out until more requirements
