### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#1221]
This is the logging ticket.

**Comment by tjwdev** [comment]
Issue: We do not want massive, unable to be analyzed logs or disparate logs across multiple boxes.

Fleshing this out into the tasks required:

1. Turn our logs into bite-sized chunks, either by space, by time, or both.
2. Aggregate the individual files into one location given a distributed installation (many boxes, many logs)
3. Create a front-end component that allows the user to search the log files and download them (zipped?)
4. Archival process in some way to prevent the number of excess files from stockpiling.

**Comment by TeddyTesfaye** [comment]
For the above tasks (1 to 4):
1. Logs will be rotated based on size and time (24 hr)
Collecting logs:
2.  A PDI transformation and Job were implemented to collect and logs from local and remote server
4 . To prevent excess files from stockpiling, a configurable sub-job runs once per day to clean up old logs (logs older than x number of days)
