### ISSUE TITLE
Filters | Destination Airport Filter | default user location IAD isn't displayed correctly. 

### ISSUE THREAD

**Issue by lnpeng** [US-CBP/GTAS#1235]
Steps to replicate:

1. Login GTAS as a user with default user location be IAD.
2. The default user location should be added as a Destination Airport filter.
3. In filters pane, see that a filter is added to Destination Airport filter text area but 'IAD' label is not displayed.
4. Check browser console and see that "Error: requiredRoles is undefined".

Browser type: Firefox

**Comment by TeddyTesfaye** [comment]
Ready for test.

**Comment by lnpeng** [comment]
Verified that the default user location IAD now is displayed correctly in the destination airport filter.
