### ISSUE TITLE
If a user changes their location setting on the webapp, the new filter doesn't apply to Flights view sometimes.

### ISSUE THREAD

**Issue by lnpeng** [US-CBP/GTAS#1236]
Steps to replicate:

1. Login GTAS as a user with default user location be IAD.
2. Noticed that flights with IAD destination are displayed in Flights view.
3. Change user location from IAD to BWI.
4. Noticed that flights with IAD destination are no longer displayed in Flights view.
5. Change user location from BWI to IAD.
5. Noticed that flights with IAD desination are no longer displayed in Flights view.

Browser type: Firefox

**Comment by TeddyTesfaye** [comment]
Ready for test

**Comment by lnpeng** [comment]
Verified that the issue had been fixed.
