### ISSUE TITLE
Add a status page on admin screen to provide information on loading and rules engine.

### ISSUE THREAD

**Issue by originalname51** [US-CBP/GTAS#1240]

**Comment by originalname51** [comment]
I decided against designing a pathway between the front end and the rules engine / loader because I like having the loading/rules running fully independent of the web application with no connection between them.

The front end will be able to provide statistics to to the users, which will allow them to make a determination if there appears to be a problem with loading (e.g. no passengers loaded in last xxx minutes, etc).

Stats I will show users:

Last message LOADED
Last message ANALYZED
Last message ERROR
Message error rates - limit 500 (configurable)
Passenger rates - limit 500 (configurable)
Message rates - Message count last 24 hours.

**Comment by lnpeng** [comment]
I uploaded new messages to GTAS Test box. Compared **Last message received** with the message file timestamp in `/data/app/gtas/out/`, **Last message analyzed** with the message timestamp in Maria DB, **Most Recent Rule Hit timestamp** with the message timestamp in Maria DB, **Passengers count from last 500 messages** with the number of passengers in **Flights view**, and **Loading/Parsing errors past 500 messages** with the number of failed messages in Maria DB. All the timestamp and count values are as expected.
