### ISSUE TITLE
Language Translation Research

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#1246]
Research ticket. Checkout existing open source tools, check with tech leads etc.

**Comment by tsegay** [comment]
@gtasautumn found the library [I18next](https://www.i18next.com/) for implementing the language translation. It is an internationalization-framework written in and for JavaScript. It has support for most javascript frameworks, including Angular1/2, Angular2, Angular2.0 and REACT.JS. 

The library is very mature and has a lot of support from the open source community.
