### ISSUE TITLE
Improve Passenger Detail Loading Time w/APIS messages

### ISSUE THREAD

**Issue by originalname51** [US-CBP/GTAS#1248]
Passenger Detail loading time with APIS message is long due to system query loading all passengers on APIS query. The passenger information is never used.

As we never use the passengers loaded significant performance gains can be made from 3s-4s load time to 0.2s-0.6s load by modifying the query to not load these passengers.

**Comment by lnpeng** [comment]
I tested that the REST api

`http://52.7.45.74:8080/gtas/passengers/passenger/195/details?flightId=8`

that utilizes the query method `ApisMessageRepository::findByFlightIdAndPassengerId` responded within 25ms.
