### ISSUE TITLE
Pax Details | Add category to watch list match

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#1252]
Passenger Details, Watch List Matches table should have the Category to alert the user about the type of match

**Comment by lnpeng** [comment]
I tested this ticket. **Add Watch List Category** works as expected in general except that it allows adding the same watch list name twice and that watch list category select has duplicate options.

**Comment by originalname51** [comment]
The following (remove .txt) will need to be run to get the database up to date with GTAS 1.5.
[wl_cat_update.sql.txt](https://github.com/US-CBP/GTAS/files/3502666/wl_cat_update.sql.txt)
