### ISSUE TITLE
Include Flight Tag Id in the views, ETL job, and neo4j flight node to support UI development

### ISSUE THREAD

**Issue by TeddyTesfaye** [US-CBP/GTAS#1253]
To support the graph UI development, add flight_tag_id in:
1.  the ETL
2.  neo4j_view
3., neo4j_hit_view
4. Flight node,

**Comment by TeddyTesfaye** [comment]
Completed. Checked into neo4j_visual branch

**Comment by lnpeng** [comment]
I will test this ticket when it is merged to dev.
