### ISSUE TITLE
Neo4j data deletion based on data retention policy

### ISSUE THREAD

**Issue by TeddyTesfaye** [US-CBP/GTAS#1254]
1. Add node_updated_on date property in all nodes (except airports)
2. Implement a sub-job that runs once in a day to remove nodes older than n days (where n is configurable in properties file)

**Comment by TeddyTesfaye** [comment]
1. The ETL transformations are updated to include node_updated_on label.
2. Job/tranformation implementation is in progress

**Comment by originalname51** [comment]
•	openssl pkcs8 -topk8 -inform PEM -outform DER -in gtas-prv.pem -out gtas-prv-pk8.pem –nocrypt is currently incorrect on document and needs to be "-".

**Comment by TeddyTesfaye** [comment]
The right ticket for the above comment/correction is #1127.  This ticket is for data deletion based on data retention policy.

**Comment by originalname51** [comment]
Yes, whoops!

**Comment by kasimhelil** [comment]
Tested the following and all works fine!
- Delete a single node
- Delete all nodes 
In order a node to be deleted, it has to be at least one day older. (We do not delete a node that are updated on the same day even if we set `EXT_VAR_DELETE_BEFORE_DAYS = 0`.
