### ISSUE TITLE
Parser Tuning | phone number

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#1257]
sample block

IFT+4:28+YY CTC M 123456789'

YY = fake carrier code

**Comment by originalname51** [comment]
The root cause appears to be the IFT taking phones as CTCM instead of CTC M. Will update special case of space (" ") between ctc and m.

**Comment by lnpeng** [comment]
I uploaded to the dev box the messages that have the following free text segments:

```
IFT+4:28+YY CTC M 123456789'
IFT+4:28+YY CTCM 123456789'
IFT+4:28+YY CTC H 123456789'
IFT+4:28+YY CTCH 123456789'
```
The messages were parsed correctly and displayed in the Phone Numbers table of the Passenger Details view.
