### ISSUE TITLE
Parser Tuning | more phone numbers

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#1258]
similar to issue #1257 , parent level

ADD++700:::::::EK CTC H 1234567890'
ADD++700:::::::EK CTC B 0987654321'
ADD++700:::::::EK CTC M 5432109876'

H = Home
B = Business
M = Mobile

At individual passenger level, in the SSR segment

SSR+CTCM:HK::YY::::::0123456789+::001'

**Comment by originalname51** [comment]
#1295 is pr

**Comment by lnpeng** [comment]
I uploaded to the dev boxes the messages that have the following address segments:
```
ADD++700:::::::EK CTC H 1234567890'
ADD++700:::::::EK CTC B 0987654321'
ADD++700:::::::EK CTC M 5432109876'
```
The messages were parsed correctly and displayed in the Phone Numbers table of the Passenger Details view.
