### ISSUE TITLE
Parser Tuning | Seat Requests

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#1261]
sample block. The 001-005 refers to the ID assigned to that pax

SSR+NSST:HK:001:YY:::SFO:IAD:UA 0226 +074J::001'
SSR+NSST:HK:001:YY:::SFO:IAD:UA 0226 +074H::002'
SSR+NSST:HK:001:YY:::SFO:IAD:UA 0226 +074G::003'
SSR+NSST:HK:001:YY:::SFO:IAD:UA 0226 +074F::004'
SSR+NSST:HK:001:YY:::SFO:IAD:UA 0226 +074E::005'

YY = fake carrier code

**Comment by originalname51** [comment]
Treating NSST as SEAT.

**Comment by originalname51** [comment]
SSR+NSST will parse exactly as a SSR+SEAT does.

**Comment by lnpeng** [comment]
I modified a PNR message and changed all "SSR+SEAT" rows to "SSR+NSST" rows. The "SSR+NSST" seat request in the message was parsed correctly and displayed in the seat info table of passenger details view page. However, the message has 6 rows of "SSR+NSST" and only one row of "SSR+NSST" was displayed. This is another issue unrelated to this PR after sync with @originalname51 .
