### ISSUE TITLE
Decouple the PNR from the DataGen, and share on GitHub

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#1267]

**Comment by originalname51** [comment]
I did not see the data generator on github.

**Comment by dje04001** [comment]
It's on the dev branch only at the moment

**Comment by originalname51** [comment]
The data generator is on github.

While the name is informative it is also long and I recommend changing it. 

I suggest making a directory structure (e.g. gtas/api-generator/v1/08/apiGenv1.0.xsl or gtas/api-generator/apiGenv1.0 - ceding some historical generators to source control).
