### ISSUE TITLE
Display Watchlist Category In Watchlist Table

### ISSUE THREAD

**Issue by originalname51** [US-CBP/GTAS#1271]
For fuzzy matches show watchlist category on front end in passenger details.

**Comment by originalname51** [comment]
Part of this ticket will be to change "Watchlist Matches" to Partial Matches to better show these are "partial" watchlist hits. I will add a row to Partial Matches that says "watchlist name"

**Comment by lnpeng** [comment]
I added a passenger to Watch List from Passenger Details view page, reset the message status back to 'LOADED' from Maria DB Client, and after the message status became 'ANALYZED', checked that the Watch List Category was displayed in Partial Hits table of the Passenger Details view page.
