### ISSUE TITLE
Revive Automatic Builds 

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#1275]
Review automated build options, including TRAVIS and Jenkins. 

Travis was configured but removed, see commit eedc57e0e31e235afa7229d9f70ba1a1e1723824. 

AC1: Dev and Master build and pass test
AC2: Dev and Master deploy to AWS test environments
AC3: This must be secure

Bonus AC: Run test on ALL branches upon a commit to that branch.

**Comment by originalname51** [comment]
Deploys 2x a day.
