### ISSUE TITLE
Research Indexing of Message Data for reporting and Kibana Canvas

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#1299]
Partners require the ability to monitor message flow by carrier, by flight, by push, and by day through a report. It appears that we could do this fairly easily in Kibana Canvas if we indexed message data.

1. Is this possible?
2. What is the level of effort required to index this data?
3. Can we use Canvas to fulfill this requirement?

**Comment by TeddyTesfaye** [comment]
Completed
