### ISSUE TITLE
GTAS Deployment Instructions

### ISSUE THREAD

**Issue by originalname51** [US-CBP/GTAS#1307]
Create GTAS deployment instructions for Physical Hardware, Review for Virtual and Cloud.

**Comment by dje04001** [comment]
Currently working on the physical hardware, step-by-step, for a centOS VM.

**Comment by dje04001** [comment]
Cloud deployment instructions are in the google drive, under deployment. Physical hardware instructions are up to date in the install.md on GitHub, and there are youtube videos on how to make your own VirtualBox.
