### ISSUE TITLE
Maven Install not pulling latest NPM repo

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS#1318]
Additions to the package.json file correctly cause the app to download new dependencies, but updates to the version number do not (always?) result in a new download. This is affecting deps installed with yarn.

**Comment by originalname51** [comment]
When updating to the most recent I needed to blow away my node_modules folder and re-download in order to build the application.

**Comment by originalname51** [comment]
Ran steps, validated lodash updated to later version.

**Comment by originalname51** [comment]
I got a no such file exception on bower.

**Comment by originalname51** [comment]
Navigating to the folder and then deleting the symlink to bower_components was how I was able to run.
