### ISSUE TITLE
Required Class Missing

### ISSUE THREAD

**Issue by DJCJohnson** [US-CBP/GTAS#1330]
I need help. 
I get build failures and am being told:
Failed to execute goal de.juplo:hibernate4-maven-plugin:1.1.1:export (default-cli) on project gtas-commons: Execution default-cli of goal de.juplo:hibernate4-maven-plugin:1.1.1:export failed: A required class was missing while executing de.juplo:hibernate4-maven-plugin:1.1.1:export: javax/xml/bind/ValidationException

I have downloaded all versions of the source code from the most recent to the oldest and I get the same response. Any suggestions?

**Comment by tsegay** [comment]
That is very strange. Do you mind sharing the tomcat logs ?

**Comment by pradyuman98** [comment]
> hibernate4:export potentially could have created a database that does not work with some special characters in our airports table. The command to create the database will not execute if the database already exist.
> 
> Please try the following steps:
> 
> 1:
> 
> `drop schema gtas;`
> 
> 2: followed by
> 
> `CREATE DATABASE IF NOT EXISTS gtas CHARACTER SET utf8 COLLATE utf8_general_ci;`
> 
> 3: followed by
> 
> `mvn hibernate:create`
> 
> If this still fails please provide your operating system and java version so we can recreate the environment.

Hey these steps didn't helped me. I'm getting the same error as above discussed. Please help.

**Comment by pradyuman98** [comment]
> hibernate4:export potentially could have created a database that does not work with some special characters in our airports table. The command to create the database will not execute if the database already exist.
> 
> Please try the following steps:
> 
> 1:
> 
> `drop schema gtas;`
> 
> 2: followed by
> 
> `CREATE DATABASE IF NOT EXISTS gtas CHARACTER SET utf8 COLLATE utf8_general_ci;`
> 
> 3: followed by
> 
> `mvn hibernate:create`
> 
> If this still fails please provide your operating system and java version so we can recreate the environment.

I'm also getting the same issue and I followed the above steps but still I'm getting error. Please Help.
