### ISSUE TITLE
APIS/PNR

### ISSUE THREAD

**Issue by DJCJohnson** [US-CBP/GTAS#1338]
How do I exactly load PNR records based on the Paxlst? I tried this but got this failure:
file: apiGen_1.0_20190802.xlsm, Response: {"status":"FAILURE","message":"C:\\MESSAGE\\apiGen_1.0_20190802.xlsm (The system cannot find the path specified)","result":null,"responseDetails":[{"attributeName":"errorCode","attributeValue":"SYSTEM_ERROR"},{"attributeName":"errorId","attributeValue":8},{"attributeName":"errorDetail","attributeValue":["Exception class:FileNotFoundException","Exception messsage:C:\\MESSAGE\\apiGen_1.0_20190802.xlsm (The system cannot find the path specified)","java.io.FileOutputStream.open0(Native Method)","java.io.FileOutputStream.open(Unknown Source)","java.io.FileOutputStream.<init>(Unknown Source)","java.io.FileOutputStream.<init>(Unknown Source)","gov.gtas.controller.UploadController.writeFile(UploadController.java:183)","gov.gtas.controller.UploadController.upload(UploadController.java:69)","sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)","sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)","sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)","java.lang.reflect.Method.invoke(Unknown Source)","org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)","org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)","org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)","org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)","org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)","org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)","org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)","org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)","org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)","org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)","javax.servlet.http.HttpServlet.service(HttpServlet.java:660)","org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)","javax.servlet.http.HttpServlet.service(HttpServlet.java:741)","org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)","org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)","org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)","org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)","org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)","org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)","org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)","org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)","org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)","org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)","org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)","org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)","org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)","org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)","org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)","org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)","org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)","org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)","org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)","org.springframework.security.web.session.ConcurrentSessionFilter.doFilter(ConcurrentSessionFilter.java:155)","org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)","org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)","org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)","org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)","org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)","com.allanditzel.springframework.security.web.csrf.CsrfTokenResponseHeaderBindingFilter.doFilterInternal(CsrfTokenResponseHeaderBindingFilter.java:52)","org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)","org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)","org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:74)","org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)","org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)","org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)","org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)","org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)","org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)","org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)","org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)","org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)","org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)","org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)","org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)","org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)","org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)","org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)","org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)","org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)","org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)","org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)","org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)","org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)","org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)","org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)","org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)","org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)","org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)","java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)","java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)","org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)","java.lang.Thread.run(Unknown Source)"]}]}
progress: 100% apiGen_1.0_20190802.xlsm
progress: 100% apiGen_1.0_20190802.xlsm
progress: 35% apiGen_1.0_20190802.xlsm
progress: 100% apiGen_1.0_20190802.xlsm
progress: 100% apiGen_1.0_20190802.xlsm
progress: 35% apiGen_1.0_20190802.xlsm

**Comment by DJCJohnson** [comment]
Can someone please guide me through the process of using PAXLST?

**Comment by dje04001** [comment]
It looks like you're trying to load an excel file in GTAS. The apiGen enables small carriers to create production UN/EDIFACT PAXLST messages by manually entering in passenger data, and generating  text files that fit that specification.

It also appears that you were attempting to use the drag and drop file uploader from the web application. That feature requires a lot of configuration and it is slated for removal. Development environments can use the message_in and message_out directories for easy message processing. These directories are set in the application properties.

**Comment by DJCJohnson** [comment]
Thank you, may you walk me through the process of using a development environment with GTAS. There is no tutorial and I’m not sure of the correct way to do it.

**Comment by dje04001** [comment]
sure thing. Please email me and we'll set something up--

david.j.ertel@gmail.com
