### ISSUE TITLE
PaxDetail - svg path error

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS#1339]
Occurring after merge of link analysis branch and dev, error in devtools is:
  `Error: <path> attribute d: Expected moveto path command ('M' or 'm'), "{{documentPath()…".`

It's a jquery error, possibly a result of a change to the jquery version in package.json, and appears to be related to the rendering of svg images by vaquita/d3 (which uses jquery) in the link analysis tab. It does not seem to affect the graph functionality tho.

**Comment by originalname51** [comment]
Validated error no longer shows up. Created #1353 while validating.
