### ISSUE TITLE
Link Analysis - memory leak

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS#1346]
There appears to be a memory leak when tabbing back to the LA page. Need to verify that the vaquita render methods are safe and possibly expose a new method to ensure the physics and fetches are all canceled on refresh.

**Comment by gtasautumn** [comment]
To test, enter the link analysis tab on the paxdetail page, and switch back and forth between tabs, ensuring that the graph remains responsive at all times (should not freeze).

Then repeat the previous test after selecting new users on the flightpax list. The graph should never display black or freeze.

**Comment by originalname51** [comment]
Did not see delays, switched between tabs and passengers.
