### ISSUE TITLE
Console Errors when clicking out of Pax Detail

### ISSUE THREAD

**Issue by originalname51** [US-CBP/GTAS#1353]
Steps to reproduce: 

1. Load into a pax detail.
2. Click out into cases and flights. The error appears to happen on some sort of timer.

![image](https://user-images.githubusercontent.com/10320916/64194647-a9516c00-ce4d-11e9-8140-8a21e0b7ec29.png)

**Comment by gtasautumn** [comment]
Fixed a pair of null references in the dep, upgraded to v1.0.9.

**Comment by gtasautumn** [comment]
vaquita is now @v1.0.9. Verify that by rerunning mvn install updates package.json under webapp/resources, and check that the error is cleared when:
  1. Entering link analysis on PaxDetail with devtools open
  2. Navigate away from PaxDetail *in the same browser tab*
  3. Resize the window

There should no longer be an uncaught TypeError error in vaquita.js on the 'clientWidth' prop of [null]

**Comment by originalname51** [comment]
Validated.
