### ISSUE TITLE
Build stage - hibernate not persisting UTF8 chars on DB creation

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS#1361]
Revisiting this ahead of the translation updates. UTF8 text is not encoded correctly from the sql scripts used during build, so that non-ascii chars are corrupted. See the carriers or airports table.

**Comment by gtasautumn** [comment]
To test, re-run mvn hibernate:create after backing up your existing gtas db. The country, carrier, and airport tables should show the correct non-Latin characters where expected, eg, running the queries below should return the comment text

   `select name from airport where city = "N'gaoundere";` -- N'Gaoundéré Airport

   `select name from country where iso2 = "AX";` -- Åland Islands

   `select name from carrier where iata = "P5";` -- AeroRepública, S.A. t/a Copa Airlines Colombia

**Comment by originalname51** [comment]
After re-running i get the following


![uploads/18351b77-9b09-43f7-9d31-a73b67d749e7/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F18351b77-9b09-43f7-9d31-a73b67d749e7%2Fimage.png)

**Comment by gtasautumn** [comment]
what's the collation on your DB?

`show variables like '%collation%'`

**Comment by originalname51** [comment]
![uploads/eaf28149-4111-47c2-b4cc-7b607ce24ddb/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Feaf28149-4111-47c2-b4cc-7b607ce24ddb%2Fimage.png)

**Comment by dje04001** [comment]
works for mysql  Ver 15.1 Distrib 10.4.6-MariaDB, for osx10.14 (x86_64) using readline 5.1
