### ISSUE TITLE
Flightpax - Grid is not sized correctly on the page

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS#1362]
It should fill the empty space in the red rectangle in the image below.

[Fake data]
![uploads/5615b8b2-6090-4e52-b885-f4937ad1263e/FlightPaxGridSize.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F5615b8b2-6090-4e52-b885-f4937ad1263e%2FFlightPaxGridSize.png)

**Comment by originalname51** [comment]
Validated in dev.
