### ISSUE TITLE
Improve Loading Time Of Passenger Page

### ISSUE THREAD

**Issue by originalname51** [US-CBP/GTAS#1368]
When clicking a passenger on a flight it is taking ~3 seconds to load.

Initial diagnostics show the  passengerRespository.findByCriteria(flightId, request); taking about a 1.3 seconds. Loading the vo is taking ~2.11 seconds (for a total of ~3.5 seconds for page load) due to an unnecessary database call in a loop.

**Comment by dje04001** [comment]
reviewed, passed.
