### ISSUE TITLE
Test all roles

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS#1401]
Need to scrub all pages for accessibility by users in each role.

**Comment by tjwdev** [comment]
All roles tested - End result is the following:

1. Roles act nearly identically to permissions barring some discrepancies in reach, we will move forward removing the discrepancies to make them proper permissions.
2. The discrepancies almost all exist around who and what is allowed to do various "case" related actions.To solve this, we will be adding a "case" based role that will have access to specifically case related components and strip out the case permissions from other roles.
3. Kibana is another discrepancy that will potentially have to be handled via another role, but is something that does not have a specific solution at the moment but should be considered as a genuine problem to be solved.
4. There are several visual buttons that exist that are unusable for given roles. We will disable those buttons depending on the role. e.g. Flights grid passenger count hyper-link


There will be new tickets created for numbers 2 and 4.
