### ISSUE TITLE
Null Pointer on Service Utils

### ISSUE THREAD

**Issue by originalname51** [US-CBP/GTAS#1403]
Null pointer at gov.gtas.services.ServiceUtil.findPassengerOnFlight(ServiceUtil.java:214)

A null check needs to be added to 
``					String paxIdTag = pax.getPassengerIDTag().getIdTag();
``

**Comment by originalname51** [comment]
1. Create message with passengers who share same first name and last name
2. run message through
3. verify message loads without throwing exception

**Comment by dje04001** [comment]
Did not receive null pointer on loading.
