### ISSUE TITLE
Language Translation | Passenger Details

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#1412]
- [x] Summary
- [x] API
- [x] PNR
- [x] Flight History
- [x] Link Analysis
- [x] Case

**Comment by originalname51** [comment]
Refer to #1431 for testing

**Comment by kasimhelil** [comment]
The following words/phrases are not being translated: 

- The labels for the nodes and relationships under link analysis
- `Leave a Comment`  on casemanual ( Click on `Create Case^` on paxdetails page, you will find the phrase above the comment box.)
- `Watch List Category` and `Category`  (Click on `Add to Watchlist^` button on paxdetails; the words are on the left sidebar that pops up)

**Comment by dje04001** [comment]
Everything looks good. All fields are translated or marked with a ^.
