### ISSUE TITLE
Good story for the live demo

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#142]
- small African country (Nigeria)
- virus outbreak
- catch a passenger paying with cash
- last minute ticket
- would have to custom make the data

**Comment by svempati2006** [comment]
In the test data scheduler job which runs every day at 6.00AM Nigerian
airports were added to generate random origin Nigerian airports and country
as Nigeria.
The data generator generates a person with form of payment as Cash.
Once the data is uploaded the query builder can pull PNR records who
brought ticket with Cash.
Code changes:  gtas-webapp/src/main/webapp/data/form_of_payment_types.json

MessageGenerator :PnrGenUtil.java , DailyJobSceduler.java


Thank you,
Srinivasarao Vempati.

*Capital Infotech Inc.*

*41969 Ural Dr.*

*STONE RIDGE.*

*VA-20105.*
*Ph:703-340-0906.*
