### ISSUE TITLE
Language translation - Case disposition

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS#1429]
the casedisposition grid and nav translations

**Comment by originalname51** [comment]
Refer to https://github.com/US-CBP/GTAS/pull/1431 for testing

**Comment by kasimhelil** [comment]
![uploads/c037de3d-d86f-4876-8fcd-fa48bc259b05/Casedisposition.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fc037de3d-d86f-4876-8fcd-fa48bc259b05%2FCasedisposition.png)

**Comment by kasimhelil** [comment]
I believe, the labels for the checkboxes under `Case Status^` should be translated.

**Comment by dje04001** [comment]
please keep in mind these status lables may be different with the new data model. The PVL only has two status types; open and dismissed.
