### ISSUE TITLE
Flights grid - hits subgrid error

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS#1430]
Several issues:
1. Double clicking a hits badge (rule hits here) generates an error as it attempts to open the subgrid
2. The subgrid never contains any data.
3. The subgrid auto-closes or never opens.
4. It's super super slow when it does open.

![uploads/41fa1495-04d6-44ef-9cdd-0b16000fd87b/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F41fa1495-04d6-44ef-9cdd-0b16000fd87b%2Fimage.png)

**Comment by kasimhelil** [comment]
Double clicking anywhere on the flight grid throws the same error.

**Comment by originalname51** [comment]
new error shows up now - appears to be related to translations
