### ISSUE TITLE
PnrGovParserTest: Failure in different timezone

### ISSUE THREAD

**Issue by yashpatil** [US-CBP/GTAS#1468]
When running a `mvn clean install` in a different timezone, the PnrGovParser `pnrDocoTest` fails while asserting the `doco issuance date` as the `docoVo.getIssuanceDate().toString()` method will format it for the local timezone. e.g.

```
org.junit.ComparisonFailure: 
Expected :Fri Dec 22 00:00:00 NZDT 2006
Actual   :Fri Dec 22 00:00:00 EST 2006
```

Referring to the EDIFACT [specifications](https://www.icao.int/Security/FAL/Documents/1-PNRGOV-EDIFACT_Implementation-Guide-13-1version-SECOND.pdf), this section contains document information for identification purposes, which would most probably omit the time information in the issuance date section:

```
A passenger by the name of Mr. John Meeks supplies a United States Redress number for his PNR:
a. For those systems using automated format:
SSR+DOCO:HK:1:AA:::JFK:LAX:0001Y28JUN//R/1234567890123///US
b. For those systems using non-automated format:
SSR+DOCO:HK:1:AA::::://R/1234567890123///US
```

Based on the above, the comparison test should not use the time component of the date.

**Comment by originalname51** [comment]
Code in dev; Yashpatil completed, I reviewed.
