### ISSUE TITLE
Paxdetails - fix translations on PNR state and Baggage pax name

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS#1512]
The translation code shows up for PNR Address grid where column = state:

![uploads/febdc604-d501-4c79-b561-5f74863ec421/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ffebdc604-d501-4c79-b561-5f74863ec421%2Fimage.png)

and the column header under Total Baggage says 'Passenger Last Name' when the full name is displayed:

![uploads/46cb99bb-9e6e-4a28-9808-9055bada800e/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F46cb99bb-9e6e-4a28-9808-9055bada800e%2Fimage.png)

**Comment by originalname51** [comment]
Validated in dev environment
