### ISSUE TITLE
Unable to save rules with dwell time entity.

### ISSUE THREAD

**Issue by copenhafer** [US-CBP/GTAS#153]
To reproduce, 

- select 'dwell time' as entity.  
- Choose either country or layover time.  
- Save rule

following error appears:

Rule Engine errors:
Unable to resolve ObjectType 'DwellTime'
Unable to resolve ObjectType 'PnrDwellTimeLink'

**Comment by svempati2006** [comment]
Code fixes were unit tested and checked into bit bucket.
