### ISSUE TITLE
Paxdetail Button's Label Translation

### ISSUE THREAD

**Issue by kasimhelil** [US-CBP/GTAS#1539]
The following words/phrases need to be translated. 
- On the main paxdetail page: `EVENT REPORT`, `NOTIFY`, and `SET TO RE OPENED`.
- On the PVL modal's paxdetail page:  `EVENT REPORT`, `ADD TO WATCHLIST`, `NOTIFY`, and `SET TO RE OPENED`.

**Comment by sylbakar** [comment]
Tested on url http://dev.wcogtas.org/gtas
On the main paxdetail page, translation has been added , which is expected. Test is passed.
On the PVL modal's paxdetail page, translation has been added, which is expected. Test is passed.
