### ISSUE TITLE
Parser | Review and update FOP parser to properly determine "OLD" payment types 

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#1541]

**Comment by dje04001** [comment]
Some carriers capture the order of payment forms in the FOP line, and the parser currenly applies the incorrect payment form to the updated payment form incorrectly.

For example, the following line would be parsed as payment form "CA" for cash, but it would also assign a credit card number "XXXXXXXXXXXX1234" to it, with the credit card company "CA"

FOP+CC:3:830:CA:XXXXXXXXXXXX1234:MMDD+CA:3:15'

Any production environment affected by this would not have loaded credit card information to the Neo4j database as a result. The messages' status would have to be set back to ANALYZED in order to repopulate Neo4j wtith the correct information.

**Comment by tjwdev** [comment]
This was unable to be replicated for the original problem. Tested against prod data en masse as well as the original deployment construction for the database. All returned loaded credit cards in our database.

This did give rise to the discovery of another bug regarding multiple FOP, this is captured inside of ticket #1600
