### ISSUE TITLE
As an admin user, I want to review a signup request so that, I can approve or deny the request. 

### ISSUE THREAD

**Issue by tsegay** [US-CBP/GTAS#1592]
As an admin user, I want to review signup requests, so that I can approve or deny the request.

related to #1552 

### Acceptance Criteria:

**Scenario 1:**

After I approve the signup request, the following outcomes are expected

`Note: ` For the email templates below, dynamic fields can be inserted in square brackets, (such as [ADMIN_USER], the placeholder will be replaced with the correct value.

1. The user gets a temporary password in the email, email language below:
     
     Subject: `<SUBJECT LINE>`
     Body: `<EMAIL BODY>`

2. The signup request gets updated to reflect the approved status. 

**Scenario 2:** 

After I deny the signup request, the following outcomes are expected:

1. The user gets a denial email, email language below:

     Subject: `<SUBJECT LINE>`
     Body: `<EMAIL BODY>`

2. The signup request gets updated to reflect thee denied status.

**Comment by dje04001** [comment]
Subject: New GTAS User Request Automated System Alert

Body:
A new GTAS user Request has been made through the application login screen with the following details

Last Name:
First Name:
Phone Number:
Email address: 
Supervisor:
Physical Location:
User ID Requested:

Please review this information carefully to prevent unauthorized access to the GTAS application. The system will automatically generate a temporary password and email it to the new user applicant upon approval in the GTAS application by an admin user.

If you wish to accept or reject this applicant, please log in to GTAS and go to Tools>Admin>Manage Users.

This email is automatically generated email. Please do not reply directly.

**Comment by dje04001** [comment]
Subject: Your New GTAS User Request has been approved 
Body:

Your New GTAS User Request has been approved

You are now able to access the application with the following credentials.

User: <UserID>
Password: <temporary password>

Please contact a supervisor or systems administrator  if you have not requested a new user to be made in GTAS.

**Comment by dje04001** [comment]
Subject: Your New GTAS User Request has been declined 
Body:


Your New GTAS User Request has been declined

Please contact a supervisor if you feel this application was declined by mistake.

Please contact a supervisor or systems administrator  if you have not requested a new user to be made in GTAS.
