### ISSUE TITLE
As an admin user, After a sign up request has been placed; I want to receive an email notification, so that I can review the request on time.

### ISSUE THREAD

**Issue by tsegay** [US-CBP/GTAS#1594]
As an admin user, After a sign up request has been placed; I want to receive an email notification, so that I can review the request on time.

related to #1552

### Acceptance Criteria:

**Scenario 1:**

After an unregistered user submits a sign up request, the following outcomes are expected:

Note: For the email templates below, dynamic fields can be inserted in square brackets, (such as [ADMIN_USER], the placeholder will be replaced with the correct value.

1. I get an email notification; email language below:

    Subject: `<SUBJECT LINE>`
    Body: `<EMAIL BODY>`

**Comment by dje04001** [comment]
Subject: New GTAS User Request Automated System Alert

A new GTAS user Request has been made through the application login screen with the following details

Last Name:
First Name:
Phone Number:
Email address: 
Supervisor:
Physical Location:
User ID Requested:

Please review this information carefully to prevent unauthorized access to the GTAS application. The system will automatically generate a temporary password and email it to the new user applicant upon approval in the GTAS application by an admin user.

If you wish to accept or reject this applicant, please log in to GTAS and go to Tools>Admin>Manage Users.

This email is automatically generated email. Please do not reply directly.

**Comment by dje04001** [comment]
Subject: New GTAS User Request Automated System Alert

A new GTAS user Request has been made through the application login screen with the following details

Last Name:
First Name:
Phone Number:
Email address: 
Supervisor:
Physical Location:
User ID Requested:

Please review this information carefully to prevent unauthorized access to the GTAS application. The system will automatically generate a temporary password and email it to the new user applicant upon approval in the GTAS application by an admin user.

If you wish to accept or reject this applicant, please log in to GTAS and go to Tools>Admin>Manage Users.

This email is automatically generated email. Please do not reply directly.
