### ISSUE TITLE
As a user I want to run rules on the APIS co-passenger count

### ISSUE THREAD

**Issue by originalname51** [US-CBP/GTAS#1678]
As a user I want to run rules on the APIS passenger count of a message

**Comment by originalname51** [comment]
initial formula: 

	@Formula("(select count(distinct pax_trip.ptd_id) " +
			"from passenger_trip_details pax_trip " +
			"where pax_trip.ptd_id in " +
			"      (select flightPax2.passenger_id from flight_passenger flightPax2 " +
			"       where  flightPax2.flight_id = " +
			"              (select flightPax1.flight_id from flight_passenger flightPax1 where " +
			"                      flightPax1.passenger_id = ptd_Id)) and pax_trip.ref_number = ref_number) ")

**Comment by originalname51** [comment]
Updating for null values:

	@Formula("( select (case when ref_number is not null then (select count(distinct pax_trip.ptd_id) "
			+ " from passenger_trip_details pax_trip "
			+ " where pax_trip.ptd_id in "
			+ " (select flightPax2.passenger_id from flight_passenger flightPax2 "
			+ " where  flightPax2.flight_id = "
			+ " (select flightPax1.flight_id from flight_passenger flightPax1 where "
			+ " flightPax1.passenger_id = 8)) and pax_trip.ref_number = ref_number)  else 0 end))")

**Comment by sylbakar** [comment]
tested the feature and it works as expected.

**Comment by originalname51** [comment]
Calculation was too expensive. Ended up storing as a value on the passenger trip details table
