### ISSUE TITLE
Session  timed out error message is not displayed when a user is automatically logged out of application

### ISSUE THREAD

**Issue by sylbakar** [US-CBP/GTAS#1716]
The error message "Your session has timed out" does not appear when a user is automatically logged out of application after a set period of inactivity. User's current page stays open.

**Comment by TeddyTesfaye** [comment]
1. The session time out issue is fixed. However, the language translation feature does not work on this popup window although the right message property placeholders were set in the code that displays this window. This needs further investigation. I created ticket #1768

**Comment by sylbakar** [comment]
I have tested on AWS dev environment on version 1.11 and found the error message "Your session has timed out"  appears when user is automatically logged out of application after a set period of inactivity which is expected.
