### ISSUE TITLE
Application allows to come back to the home page with browser forward button

### ISSUE THREAD

**Issue by sylbakar** [US-CBP/GTAS#1717]
Login the application. Click on browser back button, it takes you to login page.
Click on browser forward button, system allows to come back to the home page.
System should ask for login again.

**Comment by tjwdev** [comment]
This may not be an issue, I'd like others to weigh in their opinions on the matter as well. From a meta perspective, If on login we receive some sort of 'auth token' that should be attached to the session, so long as that token is live, so too should we be allowed to access the application.

I do not necessarily see pressing the back/forward button, or even to the extent of typing in the direct link to the login screen as signaling a 'log-out' action. I would believe your session is still alive and your token still authorized to access the application.

That said there is a secondary question this brings up that goes along the lines of: "Should the login screen, if you are authorized in a still live session, kick you forward into the landing page?", but that's neither here nor there in direct regards to this ticket.

**Comment by sylbakar** [comment]
It has been resolved in new UI.
