### ISSUE TITLE
Bag weight qualifier in API data may be incorrect

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#1745]
There is a discrepancy for data between PNR and API data for baggage weights. PNR is being handled correctly, however it appears that in some cases the PNR tab is displaying X kg and the API tab is displaying 2.2 * X kg. 

This is either an issue with the data generator, or there is an issue converitng API bag weights into kg.

**To Reproduce**
1. Go to flight pax 392912/1884 in dev
2. Click on the API tab, notice the total bag weight
3. Click on the PNR tab, notice the total bag weight, and notice how they do not track.

**Expected behavior**
In a production environemnt that is receiving the latest specefication for API that includes explicit total bag weight, and PNR data, we would expect these values to track most of the time.

**Screenshots**
<img width="502" alt="Screen Shot 2020-03-08 at 4 21 40 PM" src="https://user-images.githubusercontent.com/20464494/76170539-3e188780-6159-11ea-80c2-4fe4c8245673.png">
<img width="583" alt="Screen Shot 2020-03-08 at 4 21 54 PM" src="https://user-images.githubusercontent.com/20464494/76170540-3eb11e00-6159-11ea-9380-c3fc6b3a601d.png">

**Comment by originalname51** [comment]
This appears to be an issue with the synthetic data generation - the message has the following on the APIS portion relating to passenger 392912.

MEA-CT--4*
MEA-WT--KGM:88*
FTX-BAG---2550508:2*
FTX-BAG---2550510:2*

**Comment by dje04001** [comment]
looks like bad data. We're overthinking this since bag weight in API is uncommon at this poitn in time.
