### ISSUE TITLE
Non-standard UNA for PNR | results in missed data in TBD segment

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#1747]
**Describe the bug**
It appears that non-standard UNA segments are causing the parser to miss data in the TBD segment

**To Reproduce**
1. Go to flight/pax 413687/1983 in dev
2. Click on the PNR tab
3. Scroll down to Total PNR Baggage
4. See the zeros for bag count/weight
5. click on the values in the table to highlight the line in the raw PNR to see the true bag count / weight

**Expected behavior**
The parser/loader should be capturing these values from the raw PNR.

**Screenshots**

THE DATA IN THIS TICKET IS SYNTHETIC.

<img width="977" alt="Screen Shot 2020-03-08 at 11 08 26 PM" src="https://user-images.githubusercontent.com/20464494/76179741-49d47000-6192-11ea-9680-cc57b7d6ebee.png">

**Comment by originalname51** [comment]
This appears to be related to the synthetic data generation - 
the raw synthetic message contains several passengers with the same RCI. 
The database has the correct bag measurement listed as well as teh same from all other passengers.

**Comment by originalname51** [comment]
closing - this is related to synthetic data generation.
