### ISSUE TITLE
Maritime Functionality (research)

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#1753]
Several cruise lines are providing pseudo API data for cruise ships, and we should add the capability to screen these travelers as well. This ticket will be the home to several work packages to decompose.

1. Research in-house solutions and exisitng data spec
2. Plan look and feel of the UI
3. Plan the data model changes to handle this modality

**Comment by TeddyTesfaye** [comment]
1. Existing data spec:
-  Maritime APIS from eNOAD (in XML format)
3. Plan the data model changes to handle this modality:
The following is a high level design of a data model required to accommodate maritime APIS in GTAS. Further analysis is required based on the current implementation of parsing, loading, and rule engine.
1.	Voyage table to store:
a.	Notice Type
b.	Voyage Type
c.	Voyage Number
d.	Closed Loop Voyage
e.	City
f.	State
Arrival Port Information
g.	Place/Anchorage
h.	Arrival Date/Time
i.	Departure Date/Time
j.	Less than 24-Hour Voyage?
Departure Port Information
k.	City
l.	State
m.	Departure Port
n.	Departure Date/Time

2.	The following maritime passenger information can be stored in passenger_detail table in GTAS
a.	Last Name
b.	First Name
c.	Nationality
d.	Country of Residence
e.	Date of Birth
f.	Gender

3.	The following maritime passenger Identification information can be store in the documents table in GTAS:
Primary Identification Information	
a.	ID Type	
b.	ID Number	
c.	Issue Country	
d.	Expiration Date	
Secondary Identification Information	
e.	ID Type	
f.	ID Number	
g.	Issue Country	
h.	Expiration Date	

4.	A passenger_voyage table to store:
a.	Embark Country
b.	Embark State
c.	Embark Port
d.	Embark Place
e.	Embark Date
f.	Debark Country
g.	Debark State
h.	Debark Port
i.	Debark Place
j.	Debark Date
k.	Record locator number

5.	A passenger_cabin table to store
a.	Cabin Number

6.	A new phone table to store phone information of each passenger in a given voyage
a.	Primary Contact Phone Number
b.	Secondary Contact Phone Number
 
7.	Address – This is the temporary address of the traveler inside the country for incoming voyage (not sure if this needs to be captured in GTAS)
