### ISSUE TITLE
Query Builder | Travel Agency City

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#176]
Querying on travel agency city, contains, "a" returns unexpected results.
![uploads/40569049-9573-41cd-9b06-304c439cf9d9/Screen Shot 2016-12-19 at 10.26.00 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F40569049-9573-41cd-9b06-304c439cf9d9%2FScreen+Shot+2016-12-19+at+10.26.00+AM.png)

![uploads/88f3cef2-4374-4b90-9f9b-a4a373d24a8b/Screen Shot 2016-12-19 at 10.26.07 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F88f3cef2-4374-4b90-9f9b-a4a373d24a8b%2FScreen+Shot+2016-12-19+at+10.26.07+AM.png)

![uploads/809bad60-c2f6-4f4d-b8e6-ce2cff06abbd/Screen Shot 2016-12-19 at 10.26.13 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F809bad60-c2f6-4f4d-b8e6-ce2cff06abbd%2FScreen+Shot+2016-12-19+at+10.26.13+AM.png)

**Comment by svempati2006** [comment]
Tested to reproduce this.The Travel agency city i had in the database is Washington and location IAD.This query pulled all the PNRS and passengers  with Travel agency city Washington.Please retest with current version and specify any odd behavior.With my local testing it's pulling the right results.
