### ISSUE TITLE
Passenger Details | API Co-Travelers not displayed

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#1790]
**Describe the bug**
Co-traveleres are typically identified by sharing a PNR record locator number. Assuming this is present in the UN/EDIFACT PAXLST message, the co-travelers should be identfifed on the Passenger Details / APIS tab. They are not displayed. This might be related to the removal of the FlightPax table in the backend

**To Reproduce**
1. Go to ~/paxdetail/2205527/10436 in the dev environment
2. Click on the PNR tab see co-travelers
3. Click on the APIS tab, see info missing in co-travelers

**Expected behavior**
Previously covered.

**Screenshots**

***This data is FAKE!***

<img width="979" alt="Screen Shot 2020-05-08 at 2 46 30 PM" src="https://user-images.githubusercontent.com/20464494/81438468-d2dc3900-913a-11ea-8c12-b30016033e4e.png">
<img width="589" alt="Screen Shot 2020-05-08 at 2 46 41 PM" src="https://user-images.githubusercontent.com/20464494/81438469-d2dc3900-913a-11ea-89aa-c3b4f6bd67cb.png">

**Comment by sylbakar** [comment]
I tested on dev env and found displaying list of co-travelers on API page as expected.
