### ISSUE TITLE
Automatic user logout causing issues logging back in

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#1791]
There are several things going wrong. If a user gets logged out automatically, they are not able to log back in, regardless if the other browser windows are closed. In some cases, the stale session is allowed to continue with some functionality, even if the continue session has been clicked in time

**To Reproduce**
1. Log in.
2. Be inactive long enough for the stale session prompt to pop up.
3. Click continue
4. Try to navigate the web app

Or

1. Log in
2. Be inactive long enough to get logged out automatically
3. Try to log back in

**Comment by dje04001** [comment]
Let's test this by deploying locally and testing there.

**Comment by sylbakar** [comment]
I have tested on local environment and found expected behavior.
