### ISSUE TITLE
mvn hibernate:create error

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#1813]
I'm getting errors when I try to script the database. I'm following the YouTube videos and ran into this issue.

Error executing DDL via JDBC Statement
 
Cause: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'PROCEDURE manualHitMakerPopulate() BEGIN SET @cnt = (Select IFNULL(MAX(id), 1) F' at line 1 Query is: CREATE OR REPLACE PROCEDURE manualHitMakerPopulate() BEGIN SET @cnt = (Select IFNULL(MAX(id), 1) FROM hit_category); START TRANSACTION; WHILE @cnt > 0 DO INSERT INTO hit_maker (hm_hit_type, hm_author, hm_hit_category) VALUES ('MANUAL_HIT', 'GTAS', @cnt); SET @DataID = LAST_INSERT_ID(); INSERT INTO manual_lookout (description, id) VALUES ('Manually Generated Hit', @DataId); SET @cnt = @cnt - 1; END WHILE; COMMIT; END java thread: main

**Comment by originalname51** [comment]
Issue caused by incorrect version of database. GTAS recommends Mariadb 10.4. Mariadb 5.5 doesn't work with the data script used on mvn hibernate create.
