### ISSUE TITLE
User gets access pages using known URLs for pages that should be inaccessible

### ISSUE THREAD

**Issue by sylbakar** [US-CBP/GTAS#1816]
**Describe the bug**
Role based  users are able to access corresponding restricted pages using known URLs
whereas they are supposed to access only their corresponding designed access pages.

1. Log in to the system as any user role except admin
2. On address bar enter any of the  URLs which is restricted to the user. 
3. System allows to access the page.

Expected behavior
System should restrict  to access the page.

**Comment by dje04001** [comment]
tested in new ui
