### ISSUE TITLE
Seating Chart:  Variable passengers per row required - per aircraft type

### ISSUE THREAD

**Issue by rafael5** [US-CBP/GTAS#1846]
Bug:  The Seating Chart  of aircraft is incorrect. 

Currently the image of the aircraft seating arrangement shows 11 passengers per row.   This is impossible. 
Even the worlds largest passenger aircraft (Airbus) has only 10 passengers per row  (3 - 4 - 3)

=> The seating chart must be a variable number, dictated by aircraft type

Thx!

**Comment by dje04001** [comment]
You're absolutely right, @rafael5 .  I can't find any record of a configuration exceediing 10 passengers in a row. The image shows a possible row "I" which appears to be avoided in the industry altogether to avoid confusion with similar-looking numbers/letters.

I wish we could implement a strategy like you mentioned, but it's not possible with API / PNR data to do this consistently. API data doesn't contain configuration type yet, and it's a conditional field in PNR data. Unfortunatley we're relagated to making a grid based on the front-left most seat assignment received for a flight, and the back-rihgt most assignment. There's no way of reliably predicting the aisles, so sometimes we'll end up with blank rows without special-casing. We might be able to react to what appear to be large empty sections or columns, and many configurations skip several row letters between business / economy plus / economy.

We're certianly open to any ideas/enhancements you have in mind, and we welcome pull requests to our code base. We're currently supporting countries that have aircraft ranging from A380s all the way to small chartered flights. In the meantime I'll check in an updated photo for the main page.

Thanks for your help!
