### ISSUE TITLE
How does the Airport Table work?

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#185]
Depending on how it's structured, we may want to add to it.

- What type of airport codes do we have?
- Do we have latitude, longitude for the airport locations?
- Do we calculate UTC time?

Some things we might want to look at are:
- confirming the actual order of the flights in the itinerary

**Comment by dje04001** [comment]
IATA, IACO airport codes
Latitude, longitude for the airport locations is included
OpenFlights.org/data.html for the airport locations, time, airlines

**Comment by copenhafer** [comment]
sources:

carriers:
https://www.census.gov/foreign-trade/reference/codes/aircarrier/acname.txt

countries:
http://www.nationsonline.org/oneworld/country_code_list.htm

airports:
http://openflights.org/data.html
