### ISSUE TITLE
How to create database tables

### ISSUE THREAD

**Issue by landon9720** [US-CBP/GTAS#189]
Trying to log into the webapp, I get: java.sql.SQLSyntaxErrorException: Table 'gtas.user' doesn't exist

**Comment by copenhafer** [comment]
Hi, did you execute the steps in the Deploy section of the Install guide (https://github.com/US-CBP/GTAS/blob/master/INSTALL.md)?  

cd gtas-commons
mvn hibernate4:export

**Comment by landon9720** [comment]
No, I did not. I found INSTALL.md seconds after I submitted this ticket. Sorry about that.
