### ISSUE TITLE
UTC Time

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#191]
I was researching ways to add UTC time to GTAS. This ticket is to help discussion after the holiday.

https://github.com/dosx/timezone-picker

http://momentjs.com/guides/

http://stackoverflow.com/tags/timezone/info

http://momentjs.com/timezone/

**Comment by jtangGitHub** [comment]
please elaborate the requirement?

**Comment by dje04001** [comment]
Jeen,

Please don't worry about this yet. It's in your backlog. Please focus on
what's in the working column, then the ready column. UTC time is a big lift
and will require more planning. Thank you--

**Comment by jtangGitHub** [comment]
UTC (and DST):

Database:
•	Data types support
https://dev.mysql.com/doc/refman/5.7/en/time-zone-support.html
•	Columns changes
•	
Server:
•	Information on airport, for example, timezone
•	Import airport table from the web (openflights, for example)
•	Convert flight date data to UTC-based 
•	Java package support (Date, Calendar, or java.time)
•	Code changes (queries)
•	
Front-end:
•	
Test:
•	Unit/Integration/Regression
•
