### ISSUE TITLE
Dashboard | Passenger count is 0 in the next 72 hours

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#202]
![uploads/ef7d33e0-549d-4c83-9d33-d7036f25ba5b/Monosnap 2017-01-18 12-01-15.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fef7d33e0-549d-4c83-9d33-d7036f25ba5b%2FMonosnap+2017-01-18+12-01-15.png)

**Comment by dje04001** [comment]
Changes have been made, however the Passenger Count appears to be pulling the flight count.
![uploads/08911c39-79f0-4307-b1f3-28f38e30fbc9/Monosnap 2017-01-27 14-28-50.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F08911c39-79f0-4307-b1f3-28f38e30fbc9%2FMonosnap+2017-01-27+14-28-50.png)

**Comment by dje04001** [comment]
front-end or back-end issue?

**Comment by jtangGitHub** [comment]
The code in the backend retrieved counts for flights and passengers separately.
Please also verify test data?

**Comment by dje04001** [comment]
Test data verified.
![uploads/90b1a713-9413-46f5-9bed-4edaba32bd9b/Untitled.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F90b1a713-9413-46f5-9bed-4edaba32bd9b%2FUntitled.png)

**Comment by jtangGitHub** [comment]
code checked in

**Comment by dje04001** [comment]
Thanks, Jeen. Looks good. I'll test it now--

**Comment by dje04001** [comment]
The dashboard window of time is not really the next 72 hours as noted by the label. It is the current calendar day, the next day, and the day after. Functionality is being added to select a UTC offset to correct the issue.
