### ISSUE TITLE
Passenger Details | Seat No. not displayed

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#205]
![uploads/4611041f-09b3-49a3-9c68-38116814df37/Monosnap 2017-01-18 15-23-25.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F4611041f-09b3-49a3-9c68-38116814df37%2FMonosnap+2017-01-18+15-23-25.png)

![uploads/8dd15be1-ae2a-42d1-b093-5167eea3e03f/Monosnap 2017-01-18 15-23-01.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F8dd15be1-ae2a-42d1-b093-5167eea3e03f%2FMonosnap+2017-01-18+15-23-01.png)

**Comment by dje04001** [comment]
Is this a back-end issue?

**Comment by jtangGitHub** [comment]
yes.

**Comment by dje04001** [comment]
Thank you, please resolve and let me know when it's ready for testing

**Comment by dje04001** [comment]
Verified that seat information is populating from APIS 02B message

**Comment by dje04001** [comment]
Seat number isn't displayed in the passenger details if APIS is the only message.

**Comment by dje04001** [comment]
UNA:+.? '
UNB+UNOA:4+LUFTHANSA:ZZ+HDQCH2X:ZZ+170307:0615+194557308++APIS'
UNH+46031207774342+PAXLST:D:02B:UN:IATA'
BGM+745'
NAD+MS+++UNITED HELPDESK SIN'
COM+044 222 222222:TE'
TDT+20+AA4381'
LOC+125+YYZ'
DTM+189:1703070615:201'
LOC+87+DCA'
DTM+232:1703070800:201'
NAD+FL+++Z:MIKE:RYAN'ATT+2++M'DTM+329:771019'LOC+178+LGW'LOC+179+KIN'NAT+2+USA'RFF+SEA:1K'DOC+P+823632598'DTM+36:150430'LOC+91+USA'DOC++123456'DTM+36:'LOC+91+'
CNT+42:1'
UNT+24+46031207774342'
UNZ+1+194557308'


![uploads/47b2b706-9b33-4fef-8a41-120289dac4e7/Monosnap 2017-03-06 18-36-49.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F47b2b706-9b33-4fef-8a41-120289dac4e7%2FMonosnap+2017-03-06+18-36-49.png)

**Comment by jtangGitHub** [comment]
the current implementation on DEV server is running with the assumption there is a possibility of multiple seat assignments for one passenger. This was waiting for Jon to fix the front end. 
In the meantime, I checked in the fix in the repository and the DEV is not updated yet.
It will fix this issue when the DEV bounce.
