### ISSUE TITLE
Email or Text "baseball card"

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#207]
I know we discussed the ability to send a message with passenger information to a list of email addresses or phone numbers. This should be in a standard format, similar to what other applications use.

**Comment by dje04001** [comment]
need to provide a mail server, integrate with our framework.

**Comment by bas69** [comment]
Start with creating a standard format (XML) baseball card(s) that can be downloaded.  The user can then encrypt/send the file anyway they choose.
