### ISSUE TITLE
Query Builder | editable text window for recreating / editing complex rules

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#208]

**Comment by dje04001** [comment]
Mike can do a better job of explaining the requirements. Let's get together to discuss when you're ready.

**Comment by originalname51** [comment]
This appears to have been finished; possible duplicate of #1071

**Comment by dje04001** [comment]
We don't need this. This was for constructing your own drools if a user
knows what they're doing. It's not really necessary since it could be fed
to the database anyways.
