### ISSUE TITLE
UI Pagination | page increment / decrement button inside of page number entry

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#212]
Is this by design? The arrow to go to the next page is right next to it.

![uploads/30682a28-bc25-4394-ad8c-7c6d0fb2eb58/GTAS 2017-01-19 15-54-10.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F30682a28-bc25-4394-ad8c-7c6d0fb2eb58%2FGTAS+2017-01-19+15-54-10.png)

**Comment by tjwdev** [comment]
It's a passive ui feature to the element we use there.
