### ISSUE TITLE
5 | Rule Hit flag not displayed

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#219]
Passenger Efrain Rempel has previously been flagged for a rule. Passenger appears in Cases view, without a manual case, but does not display rule hit flag.

Rule Test 1 Cit = AIA
Genger = F
![uploads/61b76c13-e430-43ab-b220-4dd8739612e5/Picture1.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F61b76c13-e430-43ab-b220-4dd8739612e5%2FPicture1.png)

**Comment by tjwdev** [comment]
The passengers are having cases opened on them, which should only happen upon having a hit, but their hit markers are coming up null on both cases and passenger's page.

![caseswithnohits](https://cloud.githubusercontent.com/assets/20208544/22476321/eb7a43fe-e7af-11e6-8c7c-3d399af843bc.png)
