### ISSUE TITLE
Where does credit card holder come from in the PNR?

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#221]

**Comment by svempati2006** [comment]
Credit card payment information comes from FOP segment in PNR.If payment is via credit card, then the provision of the cardholder name is via the IFT if different from the passenger.
Examples of FOP (Form of payment)..

1. Paid with an American Express card, with an expiration date of 12/11
FOP+CC::416.00:AX:373212341234123:1211’

2. Old form of payment was VISA card with an expiration date of August, 2013
FOP+CC:2:628.32:VI:4235792300387826:0813’
