### ISSUE TITLE
How could we set up a rule for overstayed visas?

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#223]

**Comment by svempati2006** [comment]
Few ideas.:
1).Find people who's country of citizenship is not embarkation country.
2).Verify if any one of the passenger in the above list didn't fly back to the origin country in six months.
Can be achieved through the passenger travel history.
Generally tourist/business visas will be issued for one month to 6 months.So if a passenger who's country of origin is not the embarkation country and if he do not have an additional travel record then we can flag him.(This may pull up the passenger records of permanent residents in those countries and we need to figure out how to filter those.May be country of residence field need to be considered)
