### ISSUE TITLE
Multiple Watch Lists

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#224]
Separating watch lists into types would be extremely helpful for the user, especially when GTAS is able to connect to shared lists, potentially including lost and stolen passports, Interpol watch lists etc. Designating internal vs. external would also be a key feature.

**Comment by svempati2006** [comment]
Code completed,unit tested and checked into GitHub.Pl review.

**Comment by svempati2006** [comment]
Define the following to move forward with this ticket.
1)Stolen passports.(The fields that need to be collected such as passport number,date of missing etc).
2).Interpol watch list(first name,last name,country of origin etc)

**Comment by dje04001** [comment]
We need the ability to add additional watch lists and to name the watch
lists.

One example would be:
KST watch list: following the passenger watch list model
Missing children: following the passenger watch list model

We wouldn't want to combine the two, or append one to the other. The rule
hit name in the hits section should be either KST or missing child.

**Comment by svempati2006** [comment]
Code completed unit tested and checked into Dev branch.
