### ISSUE TITLE
2 | UNEDIFACT 02B | Embarkation Airport

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#227]
Embarkation Airport field is not populating from this type of APIS file.

Test data file has 240 instances of known port of embarkation.
Query results negative.

**Comment by dje04001** [comment]
Tested 20170330 at 1309. Will wait until next deployment to DEV to review again in case code was checked in already.

**Comment by svempati2006** [comment]
Loaded test data in the file 227.txt and the Embarkation Airport loaded correctly.Please verify the same.

**Comment by dje04001** [comment]
This appears to be a front-end issue. Queried on the flight, embarkation airport/country, debarkation airport/country and it worked before code fix was deployed.
