### ISSUE TITLE
Flight Details | Origin Country

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#228]
Country of origin not populated for airport DBX.

Srini, please run separate queries for:

All airports that do not have a country.
All countries that do not have an airport.
![uploads/fab2e105-7a1e-47a7-86b6-09ff2d7de6ec/Monosnap 2017-02-03 01-00-08.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ffab2e105-7a1e-47a7-86b6-09ff2d7de6ec%2FMonosnap+2017-02-03+01-00-08.png)

**Comment by svempati2006** [comment]
We do not have an airport with airport code iata=DBX. The test data that we are using might be corrupted.

**Comment by svempati2006** [comment]
Airports that donot have Country code in our DB..

"name"
"Owando"
"Ouesso"
"Ndjili Intl"
"Ndolo"
"Muanda"
"Kitona Base"
"Bandundu"
"Kikwit"
"Mbandaka"
"Gbadolite"
"Gemena"
"Kotakoli"
"Lisala"
"Kisangani Simisini"
"Matari"
"Bunia"
"Buta Zega"
"Bukavu Kavumu"
"Goma"
"Kindu"
"Lubumbashi Intl"
"Kolwezi"
"Kalemie"
"Kamina Base"
"Kananga"
"Mbuji Mayi"
"Jerusalem"
"Midway Atoll"
"Gwangju"
"Jeon Ju"
"Yeosu"
"Sokcho"
"Gangneung"
"Jeju Intl"
"Jinhae"
"Gimhae Intl"
"Ulsan"
"A 511"
"Seoul Ab"
"Osan Ab"
"Gimpo"
"Suwon"
"Pohang"
"Daegu Ab"
"Yecheon"
"Canouan"
"Mustique"
"E T Joshua"
"Luang Phabang Intl"
"Pakse"
"Phonesavanh"
"Savannakhet"
"Sam Neua"
"Wattay Intl"
"Macau Intl"
"Danang Intl"
"Hanoi Gia Lam"
"Kep"
"Noibai Intl"
"Nhatrang"
"Phubai"
"Phu Quoc"
"Tansonnhat Intl"
"Ann"
"Anisakan"
"Bagan"
"Coco Island"
"Heho"
"Hommalinn"
"Kengtung"
"Kyaukpyu"
"Lashio"
"Lanywa"
"Mandalay Intl"
"Myeik"
"Myitkyina"
"Momeik"
"Mong Hsat"
"Nampong"
"Namsang"
"Hpa An"
"Putao"
"Pyay"
"Shante"
"Sittwe"
"Thandwe"
"Tachileik"
"Taungoo"
"Yangon Intl"
"Incheon Intl"
"Suai"
"Presidente Nicolau Lobato Intl"
"Cakung"
"Yasser Arafat Intl"
"Bagan Intl"
"Xieng Khouang"
"Phu Bai"
"Luang Namtha"
"Oudomxay"
"Magwe"
"Khamti"
"Dalat"
"Dong Hoi"
"Rach Gia"
"Ca Mau"
"Chu Lai"
"Dong Tac"
"Duong Dong Airport"
"Muan"
"Bagan"
"Samjiyon"
"Johnston Atoll"
"Cheongju International Airport"
"Sacheon Air Base"
"Wonju Airport"
"Mokpo Airport"
"Kunsan Air Base"
"Ilebo Airport"
"Lodja Airport"
"Tshikapa Airport"
"Basankusu Airport"
"Basango Mboliasa Airport"
"Nioki Airport"
"Inongo Airport"
"Tshimpi Airport"
"Boma Airport"
"Union Island International Airport"
"J F Mitchell Airport"
"Yangyang International Airport"
"Ban Huoeisay Airport"
"Kontum Airport"
"Buon Ma Thuot Airport"
"Cat Bi International Airport"
"Cam Ranh Airport"
"Co Ong Airport"
"TrÃ  NÃ³c Airport"
"Dien Bien Phu Airport"
"Phu Cat Airport"
"Pleiku Airport"
"Vinh Airport"
"Banmaw Airport"
"Dawei Airport"
"Kawthoung Airport"
"Loikaw Airport"
"Mawlamyine Airport"
"Pathein Airport"
"Pakhokku Airport"
"Grytviken"
"Naypyidaw"
"Kyauktu"
"Bokepyin"
"Grytvyken"
"Macau Ferry Pier"
"Chongjin Airport"
"Haeju Airport"
"Jungseok"
"Wake Island Afld"
"Phan Rang Airport"
"Na-San Airport"
"Monywa Airport"
"Busan"
"Busan"
"Donghae"
"Macau Taipa Ferry Terminal"
"Macau Taipa Ferry Terminal"
"Ye"
"NAYPYITAW"
"Gimpo International Airpot"
"Saravane Airport"
"Sondok Airport"
"Samjiyon Airport"
"Chongjin Airport"
"Train Station"
"Kasongo Lunda"
"Tho Xuan Airport"

**Comment by svempati2006** [comment]
175 records out of 8101 airport entries.
