### ISSUE TITLE
2 | Query Builder | Searching for Null values

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#230]
The user needs the ability to search for null values.

**Comment by jtangGitHub** [comment]
Does the requirement specify particular query attributes or ALL query attributes can have null values?

**Comment by dje04001** [comment]
All would be preferred, but if the LOE is large, I'd like to prioritize by:

Document Number
Document Issuance Country
Document Expiration Date
Document Type
Last Name
First Name
Middle Name
DOB
Citizenship
Embarkation Airport
Debarkation Airport

Any other recommendations?

**Comment by jtangGitHub** [comment]
Yes. there are changes and testing. 


I can work on the attributes (related to Document and Passenger) you mentioned in the beginning.
And then second batch of attributes (Flight) thereafter.

**Comment by tjwdev** [comment]
Hey Jeen, I've pushed an updated entities.json. We do have the option to pass null/not-null, I'm not 100% what it's going to look like on the back-end for querying, but it should be testable once you pull down the new file. I've attached the is_null, is_not_null to all of the above criteria.

**Comment by jtangGitHub** [comment]
Thanks. I will play with it first.

**Comment by dje04001** [comment]
Probably still too early to test, but here's the error I get if I try to search for passport no. = null

![uploads/7d69cede-97ae-42ca-8adb-38d8235df845/Screen Shot 2017-02-13 at 10.17.58 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F7d69cede-97ae-42ca-8adb-38d8235df845%2FScreen+Shot+2017-02-13+at+10.17.58+AM.png)

**Comment by jtangGitHub** [comment]
It seems to me you were testing the NULL on Targeting Rule instead of QueryBuilder, right?
Is this ticket for Querys?

**Comment by dje04001** [comment]
You're right, Jeen. I shouldn't use Query Builder / Rule builder synonymously. I would like this functionality for the Rule Builder as well.

**Comment by jtangGitHub** [comment]
In the implementation of Document table, the document number and document type is NOT allowed to have null value. So do we need to modify those table columns settings to accommodate the business case?

**Comment by dje04001** [comment]
GTAS will throw an exception if APIS message is missing LN or FN.

**Comment by dje04001** [comment]
GTAS will throw an error if any document is missing its number.

**Comment by dje04001** [comment]
Null query on Document Issuance Country: Pass
Null query on Document Type: fail

**Comment by jtangGitHub** [comment]
As i mentioned before. the document NUMBER and  the document TYPE is NEVER null values in the DB.
Since the parser or loader will throw the exception when messages are processed.

All the issues are related to Parser/Loader. 

Rule builder or Query builder?

**Comment by dje04001** [comment]
I got just a document number to load, with no other document-related data
items.

**Comment by jtangGitHub** [comment]
yes. if you load ONLY document number and with document type null value the system will throw exception. the paser/loader needs both with valid values. That is, the document within the message need to contain both number and type.

**Comment by jtangGitHub** [comment]
just test Query builder with document type is null return no records. will check rule builder soon.

**Comment by jtangGitHub** [comment]
rule builder with document type is null returns no hit, meaning the rule builder was running okay.

**Comment by jtangGitHub** [comment]
Also if i remember correctly, the FN and LN are required fields for a passenger. Srini can verify this.

**Comment by svempati2006** [comment]
Yes,
FN and LN are required fields.


Thank you,
Srinivasarao Vempati.

*Capital Infotech Inc.*

*41969 Ural Dr.*

*STONE RIDGE.*

*VA-20105.*
*Ph:703-340-0906.*
