### ISSUE TITLE
Database | Anguilla (AIA) airports (AXA) Clayton J. Lloyd International Airport not in database 

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#233]
Need to verify list of countries and airports are correct and complete.

**Comment by svempati2006** [comment]
Loaded the data into DB changing the collation to utf8_general_ci and most of the countries and airport data got into DB without issues.
Still the country code shows null for 175 airports.The data for airport code AXA (Name=Wallblake) is loaded with country code AIA which is Anguilla.The data we are using is showing the airport name as Wallblake and even google entry shows the same.Clayton J. Lloyd Intnl might be the recent new name.Trying to get open source data to update the existing table data.

**Comment by dje04001** [comment]
Our airports table is from https://github.com/jpatokal/openflights/blob/master/data/airports.dat, and appears to have some outdated information where airports have been renamed.
