### ISSUE TITLE
Admin | Upload | Delete All Messages

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#239]
Does not properly clear out all tables. Dwell Time for example still persists.

**Comment by dje04001** [comment]
It would be great if clearing out the messages didn't clear out the rules/queries saved. This would make testing a lot easier.

**Comment by jtangGitHub** [comment]
The purpose of this functionality is to delete all records on all tables. Do you want to change this functionality just for testing purpose?

**Comment by tjwdev** [comment]
Perhaps we don't need to adjust the current function and more-so build a separate call that merely removes the flights/passengers but leaves the queries/rules in place?

**Comment by jtangGitHub** [comment]
another widget in front-end just for testing?

**Comment by tjwdev** [comment]
Possibly; To be fair, the name "Delete All Messages" isn't quite cut and dry that you're going to also remove queries or rules.

**Comment by jtangGitHub** [comment]
the use case also deletes all messages related records such hit, audit.error, etc.

**Comment by jtangGitHub** [comment]
code checked in

**Comment by jtangGitHub** [comment]
- fix code checked in.
- wait for next deployment. 
- the saved query from query builder is removed in current deployment.

**Comment by dje04001** [comment]
Queries are still deleted. Please update to prevent deletion of queries when executing the delete all messages function.
