### ISSUE TITLE
Parsing & Loading Messages | Not behaving properly [238?]

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#240]
This may relate to the removal of the index in ticket 238. Test files are in the google drive. The two APIS messages and the PNR message all work independently, however when used together, clicking the number of passengers in the flights view returns no passengers.

**Comment by dje04001** [comment]
![uploads/26adc5bf-b170-4286-bc8c-2f7c851fde0a/screencast 2017-02-24 10-07-18.gif](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F26adc5bf-b170-4286-bc8c-2f7c851fde0a%2Fscreencast+2017-02-24+10-07-18.gif)

**Comment by jtangGitHub** [comment]
DEV server?

**Comment by svempati2006** [comment]
Can you send us the files.I didn't find the file with flight number QR1025.


Thank you,
Srinivasarao Vempati.

*Capital Infotech Inc.*

*41969 Ural Dr.*

*STONE RIDGE.*

*VA-20105.*
*Ph:703-340-0906.*

**Comment by jtangGitHub** [comment]
Jonathon and I found out this issue and I checked in the back end code fix yesterday.
the issue might be multiple seat assignments per passenger.
Jonathon is working on front-end fix.

**Comment by dje04001** [comment]
DEV server is the only server we have now.

**Comment by jtangGitHub** [comment]
i ran the test data provided within the LOCAL DEV environment and worked.

**Comment by svempati2006** [comment]
Loaded the test data and with latest code build, its working fine.No Issues
found as reported.


Thank you,
Srinivasarao Vempati.

*Capital Infotech Inc.*

*41969 Ural Dr.*

*STONE RIDGE.*

*VA-20105.*
*Ph:703-340-0906.*

**Comment by dje04001** [comment]
relates to multiple seat assignments for one passenger on APIS message.
