### ISSUE TITLE
Database & Front-End Inconsistency for Flight Direction 

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#241]
The front-end options for filtering on direction do not match the back-end, which may not accommodate all of the possible direction types indicated in the messages received. The TDT and LOC codes in the APIS message contain valuable information about direction/continuation.

**Comment by svempati2006** [comment]
Modified logic to assign "A" for Any and removed "OTH", Added "C"  in flight direction table to make it consistent with loader assigned values.
