### ISSUE TITLE
If second Document is missing Document Number, message is rejected.

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#243]
If a traveler is traveling with two documents, one with a document number and one without, the entire message is rejected.

**Comment by dje04001** [comment]
Mandatory: issuance country, issuance date, document type, document number.
remove the constraint in the logic for the second document.

**Comment by dje04001** [comment]
Test data is in the google drive in folder 243. Database isn't showing an error, however data is not loaded.

**Comment by jtangGitHub** [comment]
if the questioned visa document number is null, do you want to keep in DB?

**Comment by svempati2006** [comment]
No.The document number is unique.Right now we are not storing them in DB.


Thank you,
Srinivasarao Vempati.

*Capital Infotech Inc.*

*41969 Ural Dr.*

*STONE RIDGE.*

*VA-20105.*
*Ph:703-340-0906.*

**Comment by svempati2006** [comment]
Fixed the code.
Earlier when Document is missing any mandatory fields such as document type and document number code used to load it into database and database failed update and throws an exception and message loading used to fail.Modification is adding validation after parsing and assigning it to parent entity only if it has all mandatory field values.
