### ISSUE TITLE
DDU - "in transit passenger" | APIS data

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#248]
Research whether or not this is parsed/loaded, if it's worth parsing and loading it.

**Comment by svempati2006** [comment]
We need to receive the close out APIS message to find the previously loaded passengers based on the reference numbers/record numbers and update their status to "Boarded" or "in Transit"
Pl see the API documentation for details.


5.5 Flight Close-Out PAXLST Message
(**B.Blankenship – inclusion of this FCO example in the Annex is at the discretion of the API CC
Committee.)**
This sample illustrates a PAXLST message that may be used to report a Flight Close-Out
message that identifies all passengers who boarded the flight identified in the message.
In this example, passengers are identified only by Passenger Recor Locator and Unique
Passenger Reference (RFF qualifiers 'AVF' and 'ABO' respectively). The expectation, in this
example, is that the passenger names (travel documentation, etc.) were collected through
previously transmitted PAXLST API submissions.
UNB+UNOA:4+XYZ+CUSTOMS+130322:0335+0000001++API'
UNG+PAXLST+XYZ AIRLINES+CUSTOMS+130322:0335+1+UN+D:12B'
UNH+5755176+PAXLST:D:12B:UN:IATA'
BGM+266+CLOB'
RFF+TN:ABC1234:::1'
TDT+20+YZ567+++AA'
LOC+125+LHR'
DTM+189:1303221615:201'
LOC+87+LAX'
DTM+232:1303221905:201'
NAD+ZZZ'
RFF+AVF:TYR123’
RFF+ABO:TYL001’
NAD+ZZZ'
RFF+AVF:TYR123’
RFF+ABO:TYL002’
NAD+ZZZ'
RFF+AVF:TYR123’
RFF+ABO:TYL003’
NAD+ZZZ'
RFF+AVF:TYR123’
RFF+ABO:TYL004’
NAD+ZZZ'
RFF+AVF:AABD55’
RFF+ABO:MCO001’
NAD+ZZZ'
RFF+AVF:AABD55’
RFF+ABO:MCO002’
NAD+ZZZ'
RFF+AVF:ZMJO6O’
RFF+ABO:VEF001’
CNT+42:7’
UNT+31+5755176'
UNE+1+1'
UNZ+1+0000001’

Also see the NAD segment which has a Value :ZZZ which will not give us a clue whether passenger is "In Transit" or not.
The NAD in group 4 will intimate if the passenger is in transit..
Ex:NAD+DDU+++SORENSEN:YNGVAR:L

**Comment by svempati2006** [comment]
Right now we are setting pax type to "C" ="Intransit_Crew" and "I" for in transit passenger".
If its simply "P" then we can interpret as not borded" and if its "I" then "Boarded or In transit"
