### ISSUE TITLE
3 | Password Strength Requirement

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#263]
Please add password strength requirements.

**Comment by dje04001** [comment]
Base requirements. Please feel free to revise as necessary

- between 10 & 20 characters
- at least one uppercase character
- at least one lowercase character
- at least one special character

Possible good ideas
- can't include user name

**Comment by jtangGitHub** [comment]
code checked in with requirements: 

1. between 10 & 20 characters 
2. at least one uppercase character
3. at least one lowercase character
4. at least one special character
5. can't include user name.
6. can't contain white space.

Also code can also process additional requirements, such as regex requirement, others.
