### ISSUE TITLE
Passenger Details | Place to store attachments, display photos

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#265]

**Comment by dje04001** [comment]
This is for the back-end component. We'll have to scope this out prior to the next sprint planning and create a front-end ticket.

**Comment by svempati2006** [comment]
Added back end support to store attachments and photos for passenger.Code unit tested and checked in to BitBucket.Feature is ready for front end to store and retrieve any type of attachment for a passenger .
