### ISSUE TITLE
5 | Flights View | List hit counter for a flight does not match the actual list hits

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#266]
![uploads/49d1c845-36e6-4a36-8d7e-30cedad32923/screencast 2017-03-30 11-04-43.gif](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F49d1c845-36e6-4a36-8d7e-30cedad32923%2Fscreencast+2017-03-30+11-04-43.gif)

**Comment by jtangGitHub** [comment]
can you forward rule and watchlist criteria? thanks.

**Comment by dje04001** [comment]
![uploads/0c178293-6889-44f5-8be8-c45ea0c8c3a7/Monosnap 2017-03-30 13-21-06.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F0c178293-6889-44f5-8be8-c45ea0c8c3a7%2FMonosnap+2017-03-30+13-21-06.png)

![uploads/4fdb689d-5c74-4fde-a4f6-06b4678d7a64/Monosnap 2017-03-30 13-21-22.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F4fdb689d-5c74-4fde-a4f6-06b4678d7a64%2FMonosnap+2017-03-30+13-21-22.png)

![uploads/358683b8-51fe-4ff0-9b28-35d0dd4584df/Monosnap 2017-03-30 13-24-22.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F358683b8-51fe-4ff0-9b28-35d0dd4584df%2FMonosnap+2017-03-30+13-24-22.png)

![uploads/e4a8e1bd-ed30-4163-a86d-e4f742f9af8c/Monosnap 2017-03-30 13-23-57.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fe4a8e1bd-ed30-4163-a86d-e4f742f9af8c%2FMonosnap+2017-03-30+13-23-57.png)

**Comment by dje04001** [comment]
just testing loe = 8

**Comment by jtangGitHub** [comment]
Reminder: when running job scheduler and rule runner, it takes minutes (1-3) to display the hits results. Both the job scheduler and rule runner are running every 2 minutes but they have different starting times.

**Comment by jtangGitHub** [comment]
Also, DEMO file contains 201 messages. consider a file usually has only one (or few) message.
