### ISSUE TITLE
ideas for the dashboard

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#267]
International flights
- How many people (resolved passengers) are arriving in the next X amount of time
- How many people (resolved passengers) are departing in the next X amount of time

- How many cases for passengers arriving in the next X amount of time are still open (not in pending closure is probably best)?
- How many cases for passengers arriving in the next X amount of time are in pending closure?

- How many cases for passengers departing in the next X amount of time are still open (not in pending closure is probably best)?
- How many cases for passengers departing in the next X amount of time are in pending closure?

**Comment by originalname51** [comment]
This can now be done with Kibana. Is this ticket still relevant?
