### ISSUE TITLE
Query Builder | Add PNR ID field

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#29]
This field is missing

**Comment by svempati2006** [comment]
Do we need to ad a filter for PNR ID  in Query Builder?Can i get the requirement or user story for this?

**Comment by svempati2006** [comment]
Hi David,
This fix was completed, unit tested and checked into github.


Thank you,
Srinivasarao Vempati.

*Capital Infotech Inc.*

*41969 Ural Dr.*

*STONE RIDGE.*

*VA-20105.*
*Ph:703-340-0906.*
