### ISSUE TITLE
charts.js and angular-charts.js missing from resources

### ISSUE THREAD

**Issue by nc-at-sp** [US-CBP/GTAS#295]
When following the install.md instructions, the system would build and deploy fine but would stop at a non-interactive login screen.

Reason: charts.js and angular-charts.js are missing from:

_.\gtas-parent\gtas-webapp\src\main\webapp\resources\bower_components_

Workaround was to run bower install from _.\gtas-parent\gtas-webapp_ prior to building

Instructions should be updated, or files should be added to repo - not sure what the desired path is.

**Comment by patriot7** [comment]
I think adding the missing files is safer.

Currently all bower components files are shipped as part of the project.

angular-chart.js dependency was introduced recently in an [update ](https://github.com/US-CBP/GTAS/commit/769f0b9087ba1ad5d9bedc95223a24725b231abf).

`bower install`  will update all other dependencies.
`bower install angular-chart.js` shoule be safer.

**Comment by patriot7** [comment]
Just found that the missing files has been added in a recent commit so this issue is no longer valid.
