### ISSUE TITLE
Parsing and loading messages with issue in passenger's gender

### ISSUE THREAD

**Issue by jtangGitHub** [US-CBP/GTAS#304]
10:57:34.313 [pool-2-thread-1] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - Data too long for column 'gender' at row 1
10:57:34.408 [pool-2-thread-1] ERROR gov.gtas.services.PnrMessageService - org.springframework.orm.jpa.JpaSystemException: org.hiber
nate.exception.DataException: could not execute statement; nested exception is javax.persistence.PersistenceException: org.hibernate
.exception.DataException: could not execute statement

**Comment by svempati2006** [comment]
Code fixed.When the expected free text differs the code is now able to recognize the right element to set the gender.
