### ISSUE TITLE
Passenger Details | Nothing is displayed

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#314]
![uploads/fde4e3d8-d717-491e-8c24-4ae7247c34f3/Monosnap 2017-04-13 17-43-28.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ffde4e3d8-d717-491e-8c24-4ae7247c34f3%2FMonosnap+2017-04-13+17-43-28.png)

**Comment by tjwdev** [comment]
This was fixed per my commit yesterday. This was due to collision with merges. When the newest build gets deployed it should resolve itself.
