### ISSUE TITLE
5 | Flights View | Hit and Watch list count

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#317]
I suspect that the hit counts aren't showing because they're outside of the 72 hours window
![uploads/b1725348-ed21-4bb7-8e88-d971ad802d00/Monosnap 2017-04-16 13-40-52.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb1725348-ed21-4bb7-8e88-d971ad802d00%2FMonosnap+2017-04-16+13-40-52.png)

![uploads/f499ab9b-00c0-4b2f-8762-3b039f8e7ac7/Monosnap 2017-04-16 13-41-15.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ff499ab9b-00c0-4b2f-8762-3b039f8e7ac7%2FMonosnap+2017-04-16+13-41-15.png)

**Comment by jtangGitHub** [comment]
The 316, 315, and 317 data sets all contain MASTER CREW LIST information which is NOT handled by parser and loader currently. So all these messages got rejected and logged.
