### ISSUE TITLE
Passengers View | Pagination issues in "ANY" filter

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#328]
Tables are not loaded with correct number of rows. Page one only has a few records, when there are well over 100 pages worth of passengers. 

![uploads/4cbb4752-4347-404c-8ac6-36ee771928c5/screencast 2017-05-01 10-26-45.gif](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F4cbb4752-4347-404c-8ac6-36ee771928c5%2Fscreencast+2017-05-01+10-26-45.gif)

**Comment by tjwdev** [comment]
This has a chance of being related to #364 . Would like to see that fixed, database cleaned if need be, then checking pagination.
