### ISSUE TITLE
Data | email address

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#330]
I'm trying to update the data generator, but I can't find which segment the email address belongs to. I don't think the system is set up properly to parse and load this data.

**Comment by svempati2006** [comment]
IFT: INTERACTIVE FREE TEXT
If the IFT free text contain CTCE code then the value of it is considered
for parsing and loading as email address.


Thank you,
Srinivasarao Vempati.

*Capital Infotech Inc.*

*41969 Ural Dr.*

*STONE RIDGE.*

*VA-20105.*
*Ph:703-340-0906.*

**Comment by dje04001** [comment]
Can you please provide an example of what will work? I tried it a few different ways, and the pnrgov guidlines doc doesn't cover email addresses very well. 

I tried IFT+CTCE TINA..BLACKBURN//GMAILCOM' and a few different variations without success.

Thank you--

**Comment by svempati2006** [comment]
The PNRGOV donot have an example to set this..
Code might work against IFT+CTCE TINA@GMAIL.COM'


Thank you,
Srinivasarao Vempati.

*Capital Infotech Inc.*

*41969 Ural Dr.*

*STONE RIDGE.*

*VA-20105.*
*Ph:703-340-0906.*

**Comment by svempati2006** [comment]
Code changes were unit tested and checked into Bitbucket.Now the parser is able to handle the Email text from IFTs.

**Comment by dje04001** [comment]
Tested in DEV, email from IFT did not make it to database.

**Comment by svempati2006** [comment]
Can you send me the test data you are using to test..

**Comment by dje04001** [comment]
Sure thing. I added a folder for 330 in the drive, and this file is also a part of the regression testing set.

**Comment by svempati2006** [comment]
Test data is not having proper IFT segment for email..

IFT+4:28 CTCE HEATHER..WONG//GMAIL.COM' (*Wrong IFT Segment*)

Code expects IFT+CTCE HEATHER..WONG//GMAIL.COM'(*Right segment for capture
Email*)


Thank you,
Srinivasarao Vempati.

*Capital Infotech Inc.*

*41969 Ural Dr.*

*STONE RIDGE.*

*VA-20105.*
*Ph:703-340-0906.*

**Comment by svempati2006** [comment]
I could able to store lot of emails today from the test data i have.

[image: Inline image 1]


Thank you,
Srinivasarao Vempati.

*Capital Infotech Inc.*

*41969 Ural Dr.*

*STONE RIDGE.*

*VA-20105.*
*Ph:703-340-0906.*

**Comment by dje04001** [comment]
I know the PNR documentation didn't cover this, but I'm pretty sure the
data i sent you emulates the production data well. Let's take a look
tomorrow.

**Comment by svempati2006** [comment]
The right segment data for capture email from free text  is
IFT+4:48::YY+CTCE SOMEBODY//GMAIL.COM'
Will modify the code to parse the above IFT data.

**Comment by svempati2006** [comment]
IFT+4:28::YY+CTCE SOMEBODY//GMAIL.COM'

**Comment by dje04001** [comment]
Tested in Dev. Ingesting this format of email is complete.
