### ISSUE TITLE
APIS Data | Address information

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#331]
The APIS messages contain address information that we should be parsing and loading, including the address where the passenger will be staying.

**Comment by jtangGitHub** [comment]
Address Reporting Rules
Address elements (Number/Street, City, State, and Postal Code) are conditional
on a number of factors. According to AFR regulations:
U.S. Destination Address is required for all passengers on Inbound flights except:
- U.S. citizens
- Legal permanent residents
- In-transit passengers
- Crew members
If a passenger is joining a ship or is en route to a foreign destination, provisions
have been defined to accept a description of the destination as follows: "Transit
to Caribbean Princess, Miami, FL, USA, 99999". This is deemed acceptable as
long as all fields contain accurate information.
AFR Regulations require Home Address, including Country, for all crew
members.

**Comment by dje04001** [comment]
I just tested this--It doesn't look like we're picking the address out of the NAD segment in APIS messages

**Comment by jtangGitHub** [comment]
Can you please upload test data file?

**Comment by dje04001** [comment]
just uploaded to google drive

**Comment by jtangGitHub** [comment]
Thanks. 
The code base in Bitbucket will be deployed to DEV environment (playground)  from now on.
