### ISSUE TITLE
PROD Data | PNR SSR Docs section has addresses that are not parsed / loaded

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#332]
It appears that the Passenger Details page is displaying the Travel Agency address instead of the Passenger's address.

**Comment by dje04001** [comment]
SSR Docs section has addressed that are not parsed / loaded

**Comment by jtangGitHub** [comment]
could not find, from PNRGOV doc,  additional information on the ticket 
about any address information on SSR DOCS section. 
Please provide more information.

**Comment by jtangGitHub** [comment]
in DOCA section

**Comment by dje04001** [comment]
In this instance it's SSR+DOCA, and it didn't pick up the address correctly.

**Comment by jtangGitHub** [comment]
Yes. will fix
