### ISSUE TITLE
Codeshare Flights | Back-End

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#333]

**Comment by svempati2006** [comment]
Added attributes isCodeShareFlight and Marketing_Flught_Number to Flight class to identify a codeshare flight and its marketing flight.Code unit tested and checked into sanandreas branch for testing.

**Comment by dje04001** [comment]
I added new synth data for a codeshare flight split amongst several
marketing carriers in the google drive, folder 333.

**Comment by svempati2006** [comment]
Code changes were unit tested and checked into Bit Bucket.Pl review.
