### ISSUE TITLE
Query Builder | Travel Agency City

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#34]

**Comment by svempati2006** [comment]
Do we need to ad a filter for Travel agency city in Query Builder?Can i get the requirement or user story for this?

**Comment by dje04001** [comment]
We do not need a separate filter. In the View/Create queries function there's a conditions window. The Travel Agency group of fields already exists, but city where the travel agency is located does not exist--only Name, ID, and Phone number.

Users may determine there is a higher degree of risk resulting from Travel Agencies physically located in a particular city, and want to include as an imput for the User-defined rule.

**Comment by dje04001** [comment]
Travel Agency City is located in the <OsiDetailList> of the PNR. It is a text field that also contains the Travel Agency phone number.

**Comment by dje04001** [comment]
I did some further research and the Travel Agency City in PNRgov is located in an IFT field. It may or may not contain the city, but it usually will. One example is the line:
IFT+4:28+TN CTCT AKL  64 9 309 9723 STA TRAVEL
"AKL" is the code for the city
"CTCT" marks the line that we want to pull the data from

**Comment by dje04001** [comment]
Please make the query builder a free text field.

**Comment by dje04001** [comment]
Using travel agency location code. Uses airport city code to look up city name. Might want to think about just leaving as three letter travel agency location.
