### ISSUE TITLE
PROD Data | Luggage Count from PNR

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#341]
There are instances on the standalone server where the luggage count isn't processed properly

**Comment by jtangGitHub** [comment]
I thought luggage count is retrieved from APIS, right?

**Comment by dje04001** [comment]
There should be two luggage count data elements. One comes directly from
the PNR. This is also the same section that has luggage weight, which we
don't parse and load yet. This will be a requirement in the near future.

We also get the number of bags from the APIS message, which may be
arbitrarily assigned to whoever the airline agent assigns the bags to in a
group when they check them in.

We need to keep both elements, and keep both separate.
