### ISSUE TITLE
PROD Data | Seat number from PNR parsing and loading

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#342]
Issue parsing and loading seat number from PNR on standalone server with prod data

**Comment by jtangGitHub** [comment]
Compared to Seat information from APIS, seat number from PNR is not accurate most of the time, if ever provided. 
Please review additional test data. (30-50 files, maybe)

**Comment by dje04001** [comment]
The issue is we're not catching seat when it shows up in the SSR section as "SSR+NSST:HK"

There are numerous instances in the file on the standalone server

**Comment by jtangGitHub** [comment]
Out current implementation do not catch seat information from PNR and will need to change
tables, hibernate declaration and PNR-Seat relationship. Same as catching bagcount information from PNR.
