### ISSUE TITLE
PROD Data | Order of TVL lines

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#343]
There are instances in prod data where the TVL lines from the PNR do NOT appear in chronological order, and are displayed on the front end as received.

**Comment by donleyac** [comment]
This may be a duplicate ticket since I did the orderBY etd for the itinerary. If there is another instance where the ordering is wrong I can update this. For now I am going to place this in review.

**Comment by dje04001** [comment]
Order is not sorted by ETD. It's the reverse of appearance in the PNR. This may be throwing off the Destination country calculation.

**Comment by dje04001** [comment]
This is the second duplicate.
