### ISSUE TITLE
PROD Data | Citizenship not captured if in second SSR line 

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#348]
There's an instance where the citizenship is not captured form the second SSR line for a passenger in the PNR message.

**Comment by jtangGitHub** [comment]
Please provide the test data file or info on the test data?

**Comment by jtangGitHub** [comment]
Could not find additional information on citizenship on SSR lines.
Please verify with the PNRGOV documentation and provide additional
information.

**Comment by dje04001** [comment]
There are about 400 instances of this on the standalone server.

**Comment by jtangGitHub** [comment]
okay. what is the segment name? SSR+??? 
Can you verify also the information on PNRGOV documentation?

**Comment by jtangGitHub** [comment]
Have you put the ticket info on gtas-ticket file on the standalone server? Could not locate this ticket.

**Comment by dje04001** [comment]
This is prod data, and the documentation is on the standalone server.
