### ISSUE TITLE
PROD Data | Parsing passenger name

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#350]
This may be a fringe case, but the system did a dreadful job of parsing the passenger name.

**Comment by dje04001** [comment]
The name was pulled from the SSR+Docs line instead of the TIF segment

**Comment by dje04001** [comment]
the code you checked in a few hours ago in commit b460fbf is for the addresses parser. I'm confused how this affects the parsing of the passenger name from the SSR+DOCS line of the PNR. Let's review this in tomorrow's scrum.

**Comment by jtangGitHub** [comment]
You are right! the fix is for additional exception i found out for addresses ticket. 
got the wrong ticket #.

**Comment by jtangGitHub** [comment]
The fix for this ticket already checked in.
