### ISSUE TITLE
Passenger Details | Seat Information

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#358]
Let's change the grid from just the name field in the table to LN, FN. It's tough to figure out what a passenger's name is once there are >2 words.

**Comment by dje04001** [comment]
My machine says pass.last and pass.first. If that's intended, no big deal. it does the job.

**Comment by tjwdev** [comment]
It's not, but it should resolve itself with a rebuild and bounce of the server. It's just not reading the property file like it should be.
