### ISSUE TITLE
PROD Data | FOP+MS ?

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#360]
Any idea what this is?

**Comment by dje04001** [comment]
appears to be misc. payment

**Comment by dje04001** [comment]
We need to make this a data element that can be queried and have rules created against. MS includes mixing points and credit card, points and cash etc.

**Comment by svempati2006** [comment]
Can you provide us the test data to capture this?

**Comment by svempati2006** [comment]
Code modifications were completed to capture
FOP+MS+CC:::MA:XXXXXXXX0338:0219'
FOP+MS'
segments for miscellaneous payments.

**Comment by dje04001** [comment]
Tested and MS now enters the database as expected. However, Query Builder does not find expected results.

**Comment by svempati2006** [comment]
Front end value is different from the value we are capturing.Correcting the
query builder to pass right values.


Thank you,
Srinivasarao Vempati.

*Capital Infotech Inc.*

*41969 Ural Dr.*

*STONE RIDGE.*

*VA-20105.*
*Ph:703-340-0906.*

**Comment by svempati2006** [comment]
Code fix checked in.Pl test when gets deployed on to DEV.

>
>>
>
