### ISSUE TITLE
Passenger Details | Rule Hits section count is off

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#363]
Sean Cober in the demo data on flight 1133 has two hits, but his hits details only has one.

**Comment by jtangGitHub** [comment]
please provide test data?

**Comment by dje04001** [comment]
The data is in the google drive. I tried loading it through the drag and drop function in DEV and the messages never made it to the database.

**Comment by jtangGitHub** [comment]
what is the name of the test data file? did not find 363

**Comment by dje04001** [comment]
It's there now. Google drive had an error syncing.

**Comment by jtangGitHub** [comment]
what is the rule criteria?

**Comment by dje04001** [comment]
The fourth rule should be <= 1 for days before travel. These are straight out of the powerpoint slides on github for the standard app demo.


![uploads/e971ae03-c1a7-4e3a-acef-a158bb4d160d/Health Outbreak.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fe971ae03-c1a7-4e3a-acef-a158bb4d160d%2FHealth+Outbreak.png)

![uploads/3e23c85e-c827-4609-ab77-a7452936cb85/last minute cash.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F3e23c85e-c827-4609-ab77-a7452936cb85%2Flast+minute+cash.png)

![uploads/35a59b45-2fef-4eaa-b388-e285bccd0143/drug cartel.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F35a59b45-2fef-4eaa-b388-e285bccd0143%2Fdrug+cartel.png)

![uploads/1d629343-8a83-4400-9f65-65b115abc444/Human Trafficking2.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F1d629343-8a83-4400-9f65-65b115abc444%2FHuman+Trafficking2.png)

![uploads/a211b8f9-69fe-4b0c-a855-feca95c89bf4/First Class Cash2.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fa211b8f9-69fe-4b0c-a855-feca95c89bf4%2FFirst+Class+Cash2.png)

**Comment by jtangGitHub** [comment]
could not reproduce the issue, reasons might be: 
1. the description of the ticket
2. the rule set
3. the data file

**Comment by dje04001** [comment]
obe.
