### ISSUE TITLE
Interpol | New Feature

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#37]
We should plan out how we could integrate with Interpol. Pie in the sky ideas.

**Comment by bas69** [comment]
I suggest starting with a query interface to the Interpol database of stolen and lost travel documents (SLTD) via i-checkit. https://www.interpol.int/INTERPOL-expertise/I-Checkit.  The interface could be implemented as a drools rule and executed when a new traveler transaction is received.
