### ISSUE TITLE
Data | Credit Card expiration date

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#370]
The credit card "expiration date" data element is configured for yyyy-mm-dd format, however we're probably not going to get the day of the month it will expire. Should probably be limited to yy-mm since that's what's typically on the credit card. Will research and add more detail to the requirements.

**Comment by dje04001** [comment]
PNR governence doc says the format will be mmyy

Note:
1. If payment is via credit card, then the provision of the cardholder name is via the IFT if different from the
passenger.
Examples:
1. Paid with an American Express card, with an expiration date of 12/11
FOP+CC::416.00:AX:373212341234123:1211’
2. Form of payment is cash.
FOP+CA::731.00'
3. Form of payment is Government receipt.
FOP+GR::200.00::AB123456'
4. Old form of payment was VISA card with an expiration date of August, 2013
FOP+CC:2:628.32:VI:4235792300387826:0813’

**Comment by dje04001** [comment]
I think this was already fixed and checked in when changing the format from "mmyy" to "MMyy" in the code. Is this correct?

**Comment by svempati2006** [comment]
Yes.


Thank you,
Srinivasarao Vempati.

*Capital Infotech Inc.*

*41969 Ural Dr.*

*STONE RIDGE.*

*VA-20105.*
*Ph:703-340-0906.*
