### ISSUE TITLE
Travel History | DEBORAH MAGNIA

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#373]
Items that are not in the current PNR are displayed in the current Itinerary section.

![uploads/b9291b64-9b5f-4dbe-8cb9-5420fffb6f03/Monosnap 2017-05-18 08-47-08.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb9291b64-9b5f-4dbe-8cb9-5420fffb6f03%2FMonosnap+2017-05-18+08-47-08.png)

![uploads/b85d7794-c398-4043-9ac5-fdd052011ebc/Monosnap 2017-05-18 08-47-42.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb85d7794-c398-4043-9ac5-fdd052011ebc%2FMonosnap+2017-05-18+08-47-42.png)

**Comment by tjwdev** [comment]
There is no current front-end filter if the back end returns flight information from flights not on the current pnr. I will add one.
