### ISSUE TITLE
Data | Credit Card sponsor

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#381]
I don't think the system is capturing the credit card sponsor correctly. Can you please send me an example of a segment that should load properly?

**Comment by dje04001** [comment]
GR.4 - form of payment information
FOP - type of form of payment, credit card info, and other form of payment
information associated with a ticket.
IFT - sponsor information
ADD - credit card billing information

**Comment by jtangGitHub** [comment]
here is a segment, from code:
Sponsor information.(IFT+4:43+TIMOTHY SIMS+2234 MAIN STREET ATLANTA, GA)

**Comment by dje04001** [comment]
I was looking for a little more insight than copying from the PNR PADIS doc. I don't see how the credit card sponsor's address is getting into the database from either the level 5 IFT segment, or the level 5ADD segment. We're not picking up the phone number from the credit card sponsor either.

**Comment by jtangGitHub** [comment]
The code did pick up the sponsor' name if it is available and update as credit card holder name. But the code did not pick up sponsor's address or phone number.
