### ISSUE TITLE
Data | review of Citizenship from foreign APIS

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#387]
I spoke with a SME yesterday, I was informed that foreign APIS data often has bogus citizenship codes. We need to make sure that codes that don't exist still get loaded to the database.

We also need to be able to query / make rules on passengers with bogus citizenship codes, i.e. create a rule on a passenger with citizenship code "XXX" OR passenger does not have recognized citizenship country.

**Comment by dje04001** [comment]
I created test data for this where every country code in the apis file is a random three-letter string. It didn't load. Test file is in the drive.

**Comment by jtangGitHub** [comment]
The parser could not extract the payload of the message.

**Comment by dje04001** [comment]
Is this an issue with the way the message was formatted, or does the system
not accept three-letter country codes that don't exist in the table?

**Comment by jtangGitHub** [comment]
The format of the message was the issue.

Also, the code base does not store any value if it does not match those in the table.

**Comment by svempati2006** [comment]
This message is treated as USEdifact by the parser and expecting CTA as
starting element..


Thank you,
Srinivasarao Vempati.

*Capital Infotech Inc.*

*41969 Ural Dr.*

*STONE RIDGE.*

*VA-20105.*
*Ph:703-340-0906.*

**Comment by svempati2006** [comment]
Changing NAT+2+PDT' to NAT+2+ADT will allow the file to load into the DB.


Thank you,
Srinivasarao Vempati.

*Capital Infotech Inc.*

*41969 Ural Dr.*

*STONE RIDGE.*

*VA-20105.*
*Ph:703-340-0906.*

**Comment by dje04001** [comment]
I thought about this, and this is a potential vulnerability in the system. A bad actor could potentially modify a document to affect the string, resulting in NAT+2+ADT and the APIS message could fail. We should consider additional validation to determining whether or not the message is UN vs. US EDIFACT.

**Comment by svempati2006** [comment]
Code completed,unit tested and checked into GITHUB.Pl review.
