### ISSUE TITLE
Database | PNR Departure Date

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#388]
The "Departure Date" Data Element is pulling from the first TVL line in the header section of the PNR. I don't think this is correct. We should probably pull the departure date/time from the individual travelers' first TVL line. What do you think?

Don't make any changes until the sprint planning session

**Comment by svempati2006** [comment]
Departure Date is specific to PNR and all the passengers associate with that PNR. I do not see any difference from first TVL and Traveller's first TVL.If you have any real PNR that has a difference then we can modify the code to collect from Travellers TVL.Please let me know.
