### ISSUE TITLE
Fix 'enter' key on filter change (flight, pax views)

### ISSUE THREAD

**Issue by copenhafer** [US-CBP/GTAS#4]
As a user I would like the enter key to consistently work when updating filters, so I can change the flight and pax views without pressing the update button.

**Comment by tjwdev** [comment]
Fixed enter key issue, angular digest was firing late to update the model when dates were changed because of the date validation aspect of the input fields. Minor delay has been added and should resolve the issue now that it allows time for the model to be updated.
