### ISSUE TITLE
Credit Card | Date format in UI

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#405]
Date in database is 2019-04-01, and should be displayed as 2019-04.

![uploads/fa94ca68-6b2d-4903-8da0-277e01f4266a/Monosnap 2017-05-30 15-07-52.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ffa94ca68-6b2d-4903-8da0-277e01f4266a%2FMonosnap+2017-05-30+15-07-52.png)

**Comment by svempati2006** [comment]
Code completed,unit tested  and checked into GitHub,Pl review.
