### ISSUE TITLE
Passenger Details | Itinerary Table

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#411]
Right now we're showing Flight Data and ETD which contains the flight date. Let's remove Flight Date, Move ETD to the left, and add ETA.

**Comment by donleyac** [comment]
There is an itinerary table in both flight history and on the pnr tab. The flight-history tab has a bit more information. Did you want me to add this ETA to the pnr itinerary?

**Comment by dje04001** [comment]
Yes, please. Does it make more sense to sort by ETD? I can't think of an
example where it would be different.

**Comment by donleyac** [comment]
yah etd makes
