### ISSUE TITLE
Data | Document expires X days after travel data element

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#426]
The same way we calculate booked X days before booking in the PNR, we need to have Document expires X days after ETD. Keep in mind that APIS is the most reliable source for Visa document information.

**Comment by svempati2006** [comment]
Code completed unit tested and checked in to GITHUB.Pl review.

**Comment by dje04001** [comment]
I don't think this should be in the Passenger table. The "days_visa_valid" data element should probably be in the documents table, and apply to any travel document (passport and visa for now).

**Comment by dje04001** [comment]
This should be part of the documents table, and this data element does not always refer to visas. It should be for a specific document. Right now if the passport is the only document, it calculates how long the passport is valid for.

**Comment by svempati2006** [comment]
Code completed unit tested and checked in to GITHUB DEV branch.Pl review.
