### ISSUE TITLE
DataGen | Uploading error

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#455]
I made some updates to the Data Generator so that we can test new functionality, but I'm getting an error message from the latest stable version when I try to upload. It's not obvious why it's failing, and it's similar to prod data.

**Comment by svempati2006** [comment]
What are the exceptions you are getting?What error message you are getting
when uploading?



Thank you,
Srinivasarao Vempati.

*Capital Infotech Inc.*

*41969 Ural Dr.*

*STONE RIDGE.*

*VA-20105.*
*Ph:703-340-0906.*

**Comment by svempati2006** [comment]
Took 455.txt file and successfully loaded the APIS message in my local without any issues.What data file you are using to reproduce this issue?

**Comment by dje04001** [comment]
Thanks, Srini. I wasn't able to replicate this error locally with the
latest version. I'll close this ticket.
