### ISSUE TITLE
Data | Total luggage weight calculation in Kg on back-end

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#466]
We need the total weight calculation to happen on the back-end, and convert lbs to kg where applicable so that queries/rules can be made in the future.

**Comment by dje04001** [comment]
Perhaps this should be part of the parsing/loading.

**Comment by svempati2006** [comment]
Code was modified to update total bag count with both excess baggage count and bag count into total bag count and converting lbs to kgs to make the baggage weight unit qualifier consistent .Unit tested the changes and checked into GitHub.
