### ISSUE TITLE
Prod Data | ADD++M phone number segment

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#468]

**Comment by dje04001** [comment]
ADD++E:::::::1234567890'

**Comment by svempati2006** [comment]
Please confirm the data segment 
ADD++E:::::::1234567890' 
and not 
ADD++M:::::::1234567890' 
for phone number

**Comment by dje04001** [comment]
ADD++E is email
ADD++M is mobile phone
And i believe ADD++H is home phone

**Comment by dje04001** [comment]
The first comment was a typo, my apologies. I'll collect

**Comment by svempati2006** [comment]
Coding completed unit tested and checked into GitHub.
