### ISSUE TITLE
Prod Data | Handling names with a 1

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#478]
-1 seems to precede a Last Name that should be ignored when it's in the middle name section i.e.

Jones/Henry/Walton-1Jones is being displayed as :

Last Name = Jones
First Name = HenryWalton
Middle Name = Walton-1Jones

**Comment by svempati2006** [comment]
Code fixed unit tested and checked into GitHub.Pl review.

**Comment by svempati2006** [comment]
Code completed unit tested and checked into GitHub DEV branch.Pl review.
