### ISSUE TITLE
Prod Data Passenger Details  | not sorting itinerary table ETD properly

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#479]

**Comment by donleyac** [comment]
Should be working, we need to test.

**Comment by dje04001** [comment]
sorting is in reverse order

**Comment by dje04001** [comment]
sorting is alphabetical vs. value driven. 2016-11-26 04:18 PM is displayed before 2016-11-26 07:35 AM.

**Comment by donleyac** [comment]
From the frontend perspective it is fine, once we convert all the dates to military time in the backend this sorting type would provide the expected order. Right now it's doing this because the date is being managed as a string and alphabetical is the only sorting for that.
