### ISSUE TITLE
Passenger Details | Document Number

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#481]
The current state only displays the documents pertaining to the traveler specified in the Passenger Details selection, however it should show all documents on that PNR.

**Comment by donleyac** [comment]
Ok I added all the documents to the pnr. Now there are two sets, one document table tied to a specific passenger which is shown in passenger detail and the pnr documents table which contains all of them on the pnr.

**Comment by dje04001** [comment]
couldn't find this either.
