### ISSUE TITLE
PNR | highlighting 

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#491]
Clicking on a PNR data element in the tables on the left-hand side should jump to and highlight the source in the PNR message.

**Comment by donleyac** [comment]
To have it work as suggested we would need to breakdown the displayed raw pnr by its chunks and label each chuck. So that when the PNR data element is clicked in the table we would call that specific label and change the display colors.

**Comment by dje04001** [comment]
Perfect. This should be pretty easy if we follow the PADIS document in the
shared drive.
