### ISSUE TITLE
License allows change, the source file headers say otherwise

### ISSUE THREAD

**Issue by netvisao** [US-CBP/GTAS#50]
The license (LICENSE.md) terms are unequivocally confusing, the license allows changes as long as the source file headers are unaltered, however these same headers stipulate that the source code is copyrighted.

It would be beneficial to all potential contributors if you could explicitly spell out whether this code is property of CBP, UNISYS corp, or the public domain?

I would suggest a thorough legal review of your licensing scheme.

**Comment by copenhafer** [comment]
Amine -- thanks for your comments.  It's currently under review by Unisys legal.  Someone from Unisys may reach out to you directly, FYI.
