### ISSUE TITLE
Last Names ending in "AVI" not parsing properly

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#505]

**Comment by svempati2006** [comment]
Can you provide more details?

**Comment by dje04001** [comment]
sure thing. just uploaded test files to the google drive.

**Comment by svempati2006** [comment]
Took test file (505.txt) from shared drive and successfully loaded into
database.All the firstnames and last names correctly parsed and loaded.
BTW the test data donot have any last name ending AVI..

[image: Inline image 1]

**Comment by dje04001** [comment]
I found a few at a glance. All passengers' full names include "avi" somewhere, but these three end in "avi" and don't parse properly. 

Pat Vaishnavi, Sarah Jahnavi, Tyson Manavi

![uploads/19b957a1-14ae-4cd1-8158-8797dc25dc13/Monosnap 2017-07-11 10-46-23.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F19b957a1-14ae-4cd1-8158-8797dc25dc13%2FMonosnap+2017-07-11+10-46-23.png)

**Comment by svempati2006** [comment]
Yes.
The name VAISHNAVI is checked for suffix and "VI" is getting recognized as
roman six and is truncated from name and added to suffix.

**Comment by svempati2006** [comment]
code fixed and checked into GitHub.Pl review.
