### ISSUE TITLE
Need an alert on front end if message fails

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#522]

**Comment by donleyac** [comment]
What do you mean by message in this context? Do you mean when you upload an apis or pnr document and it fails?

**Comment by tjwdev** [comment]
I think so. Right now it merely responds successfully regardless of the
result.

**Comment by dje04001** [comment]
Exactly. If a message is received and it bounces, we should have some way
to notify admins that it happened. I don't know what our options are, but
maybe a number badge in the header menu that brings up a list of the
message ids / timestamps that bounced would be great. And maybe a toast
message when it happens?

**Comment by dje04001** [comment]
I don't want to confuse this with the drag n' drop admin screen. it needs
to be for incoming messages through the queue or backend loader.
