### ISSUE TITLE
APIS Flight Pax Table

### ISSUE THREAD

**Issue by donleyac** [US-CBP/GTAS#523]
The following is the solution we discussed:
- Add Apis_Flight_Pax Table: 
    - Columns are [apis_message_id,  passenger_id, flight_id, embarkation, debarkation, port of first arrival, residence country, traveler type, installation address]
    - Installation address is the address the passenger will be staying at after arrival. There is no guarantee it will be actually on the message. Let's treat this like an optional nullable column.
- Modify Apis_Message Table: 
    - Remove [Bag Count, debarkation, embarkation, port of first arrival, residence country, traveler type, installation address]
    - Remove Association Tables [apis_message_flight, apis_message_passsenger]
 
- Modify Passenger Table: Remove [Embarkation, embark_country,  Debarkation, debark_country]

**Comment by donleyac** [comment]
Dave also brought up that the apis message maintains co-travelers. the apis has this "RFF+" message segment. If two travelers both contained "RFF+ABC123" in their respective lines in the apis message, we'd know they're co-travelers. We should add a column to the apis_flight_pax table denoting the co-traveler group id.

**Comment by svempati2006** [comment]
Back end changes were completed, unit tested and checked into Github.

**Comment by svempati2006** [comment]
RFF requirement is not clear.
i found the below from specification.which doesnt tell any thing about co traveller.pl clarify..

RFF+AVF:WWHPDS’ Indicates passenger reservation reference number
RFF+ABO:BA1321654987’ Indicates Unique Passenger Reference
RFF+SEA:22A’ Indicates assigned Seat identification
RFF+AEA:123456789’ Government agency reference number (Optionally issued by a
state to facilitate booking and travel).
RFF+CR:ABC123’ Customer Reference Number. Frequent flyer or frequent traveler
reference.

**Comment by dje04001** [comment]
Passengers on the same PNR should have the same RFF+AVF

Passenger 1 RFF+AVF:WWHPD
Passenger 2 RFF+AVF:WWHPD

It should be safe to assume that passengers on the same flight with the
same 5 PNR record locator are co-travelers.

**Comment by svempati2006** [comment]
We have another ticket for this.
I will add a field to passenger table to store this number from APIS message.We can query the co travelers using this reference number.What do you think?

**Comment by dje04001** [comment]
I think that will work. Thank you--

**Comment by dje04001** [comment]
This was a big ticket and most of the work outlined is complete and tested. The remaining work has been broken down in the milestone, " ".
