### ISSUE TITLE
Passengers | hit counts not displayed

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#527]

**Comment by donleyac** [comment]
Similar to the email addresses, if there a no hit counts the card will not show. However, I can make the card always show.

**Comment by dje04001** [comment]
This is on the passengers view,  in the grid, rather than pax details.

**Comment by donleyac** [comment]
So is this the same issue as #562 because the flags are showing for me?

![image](https://user-images.githubusercontent.com/7605602/29032129-630f1c90-7b5e-11e7-8692-87d59e959a75.png)

**Comment by dje04001** [comment]
can't replicate after a fresh build on my local.
