### ISSUE TITLE
Set Installation Country

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#528]

**Comment by svempati2006** [comment]
Need the following to move forward..
1).Do you need this to be configured through the admin page or through the property files or just a database entry?
2).What kind of functionality you are expecting ?Most of the code do not use this so we need to identify the code that can be modified to use this newly added functionality.

**Comment by dje04001** [comment]
We just need a simple way to configure at time of installation, or at least
document the places where the country needs to be set.

**Comment by svempati2006** [comment]
Created HomeCountrySetup file and uploaded to master branch which describes how to configure the HomeCountry at the time of installation.

**Comment by svempati2006** [comment]
Updated the guide with usage of HOME_COUNTRY and DASHBOARD_AIRPORT.Created one extra entry in app_configuration table via gtas_data.sql file to store DASHBOARD_AIRPORT value at the installation.
The hardcoded values for "IAD" in the file 
/GTAS-master/gtas-parent/gtas-webapp/src/main/webapp/dashboard/DashboardController.js: 
need to be replaced with "DASHBOARD_AIRPORT" value from the app_configuration table.
A Ticket need to be opened for UI developers to modify the above.
