### ISSUE TITLE
Current Tab highlighting

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#538]
Slight bug in common framework that shows an underscore for cases when the user is in pax details. 

![uploads/85b33b9f-ba64-419d-a061-f7044dd0a2dd/Monosnap 2017-08-01 17-38-44.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F85b33b9f-ba64-419d-a061-f7044dd0a2dd%2FMonosnap+2017-08-01+17-38-44.png)

**Comment by donleyac** [comment]
Ok I am reworking how we perform active tab. Now it's based on url. Right now the three tabs will only highlight on /flights /passengers and /cases. Nothing will highlight for flightpax and paxdetail. If you want I can make flight also highlight for flightpax and passenger highlight for paxdetail.
