### ISSUE TITLE
Conduct Thorough Security Review | "You are giving out private information"

### ISSUE THREAD

**Issue by lostinblue** [US-CBP/GTAS#543]
Seems you need to take some workshops on Git, maybe instead of making peoples life harder with poorly understood math and spend this time trying to migrate US govt computers to Linux instead of Windows and save literally billions. Even the smallest amount of time and money put towards improving healthcare in america would save far more people than the combined positive effects careers of every member of Homeland Security combined. 

Your program seems like it would just make people guilty by association, its not very well thought out beyond your massive security mistake you made.

**Comment by dje04001** [comment]
I appreciate your feedback. Please elaborate on the security risks you see. The application is meant for goverment agencies to use PII responsibly, not expose it to the public.

**Comment by lostinblue** [comment]
You have several major security problems :\

**Comment by lostinblue** [comment]
Not that I have a copy, but one can with not much knowledge get a copy of your production MariaDB with all the credit card information. You should fix that...

**Comment by dje04001** [comment]
Thanks for the heads up. I'm not technical, but I will have an expert review it. We don't want to hand out credit card info. We will take your feedback seriously.

PNR data provided from airlines would never include the full number. The middle five digits or so are always redacted. 

I'm not sure if the documentation covers this properly, but this application isn't about the US. It's not for the US. It's designed to expedite travel processing, and improve global security. Many are already developing similar systems, and the US sharing its know-how hoping to engage a community of developers to improve it for everyone.
