### ISSUE TITLE
PNR Tab | email address card isn't being displayed

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#544]

**Comment by donleyac** [comment]
The email address card is hidden if they do not have >0 emails. I can change it so it always shows, to me it looks a little weird in that case because it just looks like a header.

**Comment by dje04001** [comment]
I can show you what I'm seeing on my local.  Looks like database is
populating,  but nothing on the front end.

**Comment by dje04001** [comment]
I can't replicate this bug anymore.
