### ISSUE TITLE
Data | trim email address in back-end

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#547]
the email addresses could be stored with a leading space. This might lead to missed query results/rule hits on exact matches. Any non-consecutive characters or leading spaces should be ignored

i.e. OSI FIRSTNAME.LASTNAME@YAHOO.COM should be:
FIRSTNAME.LASTNAME@YAHOO.COM

also the domain needs to be trimmed. the last @ should start the domain name, and the last "." and appended characters should determine the end of the domain. any delimiting character after that should be ignored. 

i.e. firstname.lastname@lasntamebiz.com@gmail.com-w/passenger1 should be:

complete address = firstname.lastname@lasntamebiz.com@gmail.com
domain = gmail.com (not lastnamebiz.com)

OSL LASTNAMEFIRSTINITIAL@MUSIC.CO.UK should be
LASTNAMEFIRSTINITIAL@MUSIC.CO.UK

**Comment by svempati2006** [comment]
Code changes were completed unit tested and checked into GitHub.Pl review.
