### ISSUE TITLE
PNR tab | travel agency name

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#552]
We need to differentiate between the messaging agency and the travel agency that made the reservation.

we should use the "agency" table and show the city, the identifier, the location, the name and the phone

**Comment by donleyac** [comment]
Current Implementation: 
![uploads/a3d27729-a9fe-4134-bf11-6993b995ae94/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fa3d27729-a9fe-4134-bf11-6993b995ae94%2Fimage.png)

The Change:
 -  Change Title from Travel Agencies to Agencies
 -  Change Country to City
 -  Maybe add a  "Type" column at the front that denotes "Messaging" or "Travel"

**Comment by dje04001** [comment]
I agree with your description

**Comment by donleyac** [comment]
I assume the type would be another value we need to parse. We currently do not have that column in the db. I can make the UI changes but I'll add Srini on this ticket as well for adding Type. 
![uploads/9d280f85-94bd-4ae8-9f87-35ffcb5294e4/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F9d280f85-94bd-4ae8-9f87-35ffcb5294e4%2Fimage.png)

**Comment by svempati2006** [comment]
Type property was added to Agency and modified parser to assign type attribute values.
