### ISSUE TITLE
UI | replace flags with hit counts on Flights, Flight-Pax, and Pasenger views

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#562]
Please use the common framework badges with red background for rule hit counts, and yellow background for watchlist counts.

**Comment by donleyac** [comment]
It will have to be yellow/black and red/white since those are the approved color combinations

**Comment by donleyac** [comment]
Also shouldn't it be reversed since watchlist is more severe than rule hits? Yellow is considered warning while red is considered danger?

**Comment by donleyac** [comment]
We can also just consider changing the test color for both. This is how it looks now, let me know what you think. 
![uploads/79d9606e-42eb-4f35-af40-69eee8965910/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F79d9606e-42eb-4f35-af40-69eee8965910%2Fimage.png)
