### ISSUE TITLE
UI | Common Framework Kitchen Sink

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#563]
Please move the items from the manage and admin drop-downs into the Kitchen Sink just to the right of the Organization Brand/Subheading. This will have to be tested so that users can only see the options they're provisioned to see.

**Comment by donleyac** [comment]
Locally I made this change. I see a problem with there being too many options and so if the screen size shrinks the navbar has to grow vertically. This causes the navbar to cover up the subnav.

**Comment by donleyac** [comment]
![uploads/25f7c52b-a59c-4452-9f9e-b9f6fce52b04/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F25f7c52b-a59c-4452-9f9e-b9f6fce52b04%2Fimage.png)

**Comment by donleyac** [comment]
![uploads/115e103b-10ac-49e5-ad19-1917677a4a8c/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F115e103b-10ac-49e5-ad19-1917677a4a8c%2Fimage.png)

**Comment by dje04001** [comment]
I think the Kitchen Sink is one long drop-down menu, and not more menu items.

**Comment by donleyac** [comment]
I probably can fit all of that if I change the left side nav items to just logos instead of the logo text combo. When you hover on the logo there will be a tooltip labeling what it is.

**Comment by tjwdev** [comment]
I'm not sure if removing the text is the way to go, simply because of the
increase learning curve in what everything is, especially since a lot of
those icons aren't necessarily intuitive.

**Comment by donleyac** [comment]
Ok so it's just a left-aligned dropdown for those 6 pages? If so what is the dropdown name going to be?

**Comment by dje04001** [comment]
left align drop-down with all remaining options (no quick query, since that's available in menu bar)
call it "Tools".

this in backlog.
