### ISSUE TITLE
Data | email | LTS+0/O/5/APE

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#567]
This LTS string is rich with email addresses

**Comment by dje04001** [comment]
LTS+0/O/5/APE FIRST.LAST@YAHOO.COM/FIRST/LAST MRS'

**Comment by svempati2006** [comment]
code completed unit tested and checked into dev branch.Pl review.

**Comment by dje04001** [comment]
tested, but unsuccessful. Perhaps the LTS is in an unexpected location. Will provide examples.
