### ISSUE TITLE
Data | email | SSR+CTCE

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#569]
SSR+CTCE:HK:1:UA:::::/FIRSTNAMELASTNAME//YAHOO.COM+::001
SSR+CTCE:HK:001:YY:::::USERNAME..//HOTMAIL.COM-1FIRSTNAMELASTNAME'

**Comment by svempati2006** [comment]
Coding completed unit tested and checked into GitHub.Pl review.

**Comment by dje04001** [comment]
This commit caught most of the SSR+CTCE emails, but there are a few small changes needed to catch all of them. I'll put some examples in the google drive for this ticket number.

**Comment by svempati2006** [comment]
Pl provide the examples.I didn't find any with the ticket number in shared drive,

**Comment by dje04001** [comment]
252967
