### ISSUE TITLE
Data | Seat | LTS+SEAT

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#570]
LTS+SEAT RS 17B LASTNAME/FIRSTNAME DL 123 DDMMMYY JFKLHR'
LTS+SEAT NR/RS 20D LASTNAME/FIRSTNAMEMIDDLENAME DL1234 16AUG17 ATLJFK'

***The number of spaces between segments varies

**Comment by svempati2006** [comment]
Code completed unit tested and checked into Dev branch.
