### ISSUE TITLE
Data | Frequent Flyer | SSR+FQTV:HK

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#572]
SSR+FQTV:HK::DL' (just the carrier code of the frequent flyer program)
SSR+FQTV:HK:1:OZ:::::/DL1234567890-LASTNAME/FIRSTNAMEMI'
SSR+FQTV:HK:1:UA:::::SSRFQTVUAHK/LH1234567890-LASTNAME/FIRSTNAME 1.1'

**Comment by svempati2006** [comment]
Code completed unit tested and checked into GitHub.
