### ISSUE TITLE
DATA | Document | SSR+DOCO

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#575]
This one is pretty important...

SSR+DOCO:HK:1:EK:::::  /V/123456789///US+::001'
SSR+DOCO:HK:001:LH:::IAD:LHR://V/1234567890123/USA+::2'

**Comment by svempati2006** [comment]
PNRGOV provide the following for SSR DOCO.Currently the code treats DOCO code to parse into Visa type.Pl provide some real segment data to analyze.
A passenger by the name of Mr. John Meeks supplies a United States **Redress number** for his PNR:
a. For those systems using automated format:
SSR+DOCO:HK:1:AA:::JFK:LAX:0001Y28JUN//R/1234567890123///US
b. For those systems using non-automated format:
SSR+DOCO:HK:1:AA::::://R/1234567890123///US

**Comment by svempati2006** [comment]
Tested in my local with below SSR sample data from PNRGOV specification and the existing code correctly parsing and storing in DB.No additional code changes are needed.Pl review and close.

SSR+DOCO:HK:1:AA::::://R/1234567890123///US'
SSR+DOCO:HK:1:AA:::JFK:LAX:0001Y28JUN//R/1234567890123///US'
