### ISSUE TITLE
Data | Frequent Flyer | LTS+0/O/SR/SSR FQTV

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#576]
LTS+0/O/SR/SSR FQTVKEHK/ KE123456789/LASTNAME/FIRST NAME'
LTS+0/O/SR/SSR FQTVDYHK1 DY123456789/LASTLAME/FIRST NAME'

**Comment by svempati2006** [comment]
Code completed unit tested and checked into GitHub.Pl review.
