### ISSUE TITLE
Data | email | LTS+0/O/28/OSI YYCTCE 

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#577]
LTS+0/O/28/OSI YYCTCE OSL FIRSTNAME..LASTNAME//HOTMAIL.COM'
LTS+0/O/28/OSI YYCTCE FIRSTNAME..LASTNAME//HOTMAIL.COM'

**Comment by svempati2006** [comment]
Code completed unit tested and checked into GitHub. Pl review.
