### ISSUE TITLE
Data | Travel Agency | LTS+0/O/28/OSI YYCTCT

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#578]
LTS+0/O/28/OSI YYCTCT DCA 123 456-7890 TRAVEL AGENCY'
LTS+0/O/28/OSI YYCTCT DCA123 456-7890 A'
LTS+0/O/28/OSI YYCTCT DCA TRAVEL AGENCY 1234567890 '

**Comment by svempati2006** [comment]
Code completed unit tested and checked into GITHUB. Pl review.

**Comment by dje04001** [comment]
- Three letters following "CTCT" with leading and trailing space should be treated as airport code. 
- Phone numbers appear to be captured properly. 
- Anything not part of the LTS - through Airport Code should be the name.
