### ISSUE TITLE
Data | Form of Payment | LTS+0/O/F/FP

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#579]
LTS+0/O/F/FP CHECK'
LTS+0/O/F/FP CCVIXXXXXXXXXXXX1234/MMYY'
LTS+0/O/F/FP CCVIXXXXXXXXXXXX1234/MMYY CV'
LTS+0/O/F/FP CASH+SFCA/EUR100.00/LAST NAME/FIRST NAME

**Comment by svempati2006** [comment]
Code completed unit tested and checked into GitHub. Pl review.
