### ISSUE TITLE
Data | Travel Agency | LTS+OSI ** CTCT

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#580]
** are wildcards for carrier code
LTS+OSI DL CTCT LON 123 4567890 TRAVEL AGENCY'
LTS+OSI KE CTCT DCA TRAVEL AGENCY 123 4567890'
LTS+OSI KE CTCT DCA  1234567890'

**Comment by svempati2006** [comment]
Code completed unit tested and checked into GITHUB. Pl review.

**Comment by dje04001** [comment]
Didn't successfully capture the Name text. Will discuss next week.

**Comment by svempati2006** [comment]
Could you pl provide the test data that you used to cause this?All three LTS segments you mentioned above were loaded to DB accurately.
