### ISSUE TITLE
Data | parse and load PNR record locator number from APIS message

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#582]
Group 4, Level 2 RFF+AVF

**Comment by svempati2006** [comment]
Code completed unit tested and checked into Github. Pl review.

**Comment by donleyac** [comment]
@svempati2006  Has the PNR record locator been added to the ApisMessage Flight-Pax? We want to use it to filter out that exist on the same apis.

**Comment by svempati2006** [comment]
Code completed unit tested and checked into GitHub.Pl review.
