### ISSUE TITLE
Classpath entry

### ISSUE THREAD

**Issue by RamakriJaya** [US-CBP/GTAS#61]
Hi

Could you please let us know what are all the jars that are to be included in the project classpath.
By inspecting the pom.xml , I have included the respective jars but still facing compilation errors in eclipse.
javax.transaction.Transactional;  javax.persistence.Index ,
I am attaching the .classpath file which we are using.

Many Thanks in advance
Jayabalambika.R
[classpath.zip](https://github.com/US-CBP/GTAS/files/471352/classpath.zip)

**Comment by copenhafer** [comment]
Are you using a maven plugin in eclipse like m2e?  http://www.eclipse.org/m2e/

If not, I recommend installing one, and importing the project as a maven project (File -> import -> existing maven project...)
