### ISSUE TITLE
Data | what is residence country?

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#611]

**Comment by donleyac** [comment]
If its on the frontend it should be country of residence.

**Comment by donleyac** [comment]
I couldn't find where this was referenced. Can you point me to the page?

**Comment by dje04001** [comment]
I was wondering where this data element came from, and if it was just a
mistake. It looks like it comes from APIS only, Group 4 LOC + 174 I the
form of a the-letter country code.
