### ISSUE TITLE
APIS Tab | Show PNR co-travelers in the table

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#617]
Limit the passengers displayed on the APIS table to exact PNR record locator matches and the current passenger instead of displaying the whole list.

**Comment by donleyac** [comment]
So the strategy would be to obtain apis message associated with the specific flight-pax. Pull all flight paxes associated with at apis message after filtering by pnr record locator tied to the initial pax id. I'll most likely create another service method that does this filtering through the db.

**Comment by donleyac** [comment]
The ref number is currently on the passenger table. It needs to be moved to the flight-pax table instead. @svempati2006.
