### ISSUE TITLE
PNR Tab | Not displaying all Frequent Traveler Numbers

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#620]

**Comment by donleyac** [comment]
The frontend is being populated by passenger.pnrVo.frequentFlyerDetails. So as long as the frequent traveler numbers are on the pnr then they should all show on the frontend.

On the backend it looks like we are iterating through all of the frequent flyer information on each pnr before sending that to the frontend. 


![uploads/49060f25-9f0a-4aac-b5f0-8a8a9ea443d4/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F49060f25-9f0a-4aac-b5f0-8a8a9ea443d4%2Fimage.png)

Looking at a complex pnr, it seems all of the frequent flyer information is there. For reference the pnr_id is 10 in this context.
