### ISSUE TITLE
Add missing fields to the FlightPax Table

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#645]
- Add Embarkation Country
- Add Debarkation Country
- Add Passenger Type

**Comment by svempati2006** [comment]
We already have TravellerType attribute in FlightPax which hold the PassengerType data.
Adding  Embarkation Country, Debarkation Country fields as part of this ticket.

**Comment by svempati2006** [comment]
Code completed unit tested and checked in to GitHub.Pl review.
