### ISSUE TITLE
Job Scheduler | Never takes a break to run rules

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#659]
It was my understanding that the loader would take break to run the rules after X messages. It's about 2,000 passengers in on a 15,000 job and it hasn't run the rules yet.

**Comment by tjwdev** [comment]
The number of passengers has no bearing on when the rules will run
unfortunately. If the number of files those passengers are contained in
number less than 500, then all of those files will run through the loader
first, then the rules will run. It is sequential, there is no check in
between those files being pulled into the datastream and its completion of
loading them into the DB. So it does take a break, and will, just after all
of those messages are done. Right now, it stops at 500 files in a single
loader run. This could be adjusted if needed.
