### ISSUE TITLE
Flight_Pax table restructuring and renaming

### ISSUE THREAD

**Issue by tjwdev** [US-CBP/GTAS#663]
Flight_Pax table is actually apis related flight_pax information. This should be renamed to something to indicate that it is that particular type of file representation. Rename to: apis_flight_pax.

debarkation, deb_country, embarkation, emb_country are all retrievable through the flight_id connection and most likely do not need to be stored in the table as well and should be removed.

**Comment by originalname51** [comment]
ended up deprecating the table and partially removing it to enable backwards compatibility.

**Comment by originalname51** [comment]
duplicate of #1758
