### ISSUE TITLE
Simple entity resolution for watch list matching

### ISSUE THREAD

**Issue by bas69** [US-CBP/GTAS#665]
Create a simple entity resolution algorithm for matching travelers with subject records (watch list items).  Matching sequence: 
(1) Travel Document # + (Travel Document Country or DoB or Last Name) based on availability of data
(2) Name + DoB

Entity Resolution will use a combination Jaro-Winkler (ER name similarity scoring), Double Metaphone phonetic matching algorithm, and fuzzy matching (GNR rules) for DoB format reconciliation.

**Comment by dje04001** [comment]
How different is this from tamr's free quickmatch?

**Comment by tsegay** [comment]
This is not different from TAMR's quickmatch. The current version (v0.2) uses Double Metaphone matching algorithm on full name (FN+MN+LN) but doesn't use Jaro-Winkler or fussy matching for DoB.
