### ISSUE TITLE
Travel History | Broken again

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#666]
![uploads/cc7f63c8-b210-466c-818e-2eb2003a9139/Screen Shot 2017-09-28 at 1.07.24 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fcc7f63c8-b210-466c-818e-2eb2003a9139%2FScreen+Shot+2017-09-28+at+1.07.24+AM.png)

**Comment by donleyac** [comment]
Do you have a test file for this, I'm having trouble recreating the issue. For pnr: 
![uploads/ba79c5fc-f0ab-434b-919e-edb88bad7798/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fba79c5fc-f0ab-434b-919e-edb88bad7798%2Fimage.png)

**Comment by donleyac** [comment]
Apis Only: 

![uploads/09cc20f1-5967-42e5-8732-8dbd3782344f/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F09cc20f1-5967-42e5-8732-8dbd3782344f%2Fimage.png)
