### ISSUE TITLE
Travel History | Current Itinerary includes flights that do not belong

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#672]
![uploads/8371211b-d042-4b7a-bab0-21125b4fc512/Screen Shot 2017-09-29 at 2.13.20 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F8371211b-d042-4b7a-bab0-21125b4fc512%2FScreen+Shot+2017-09-29+at+2.13.20+PM.png)

**Comment by donleyac** [comment]
Is there specific github ticket files with same passenger on multiple flights. Would like to upload those for testing.

**Comment by dje04001** [comment]
I thought this was from my local, but I did a quick grep on the folder for Millie Kingsley in the google drive for issue 636 and only came up with one flight. This comes from a mixture of files from the testers and me, so I'll have to recreate it.

**Comment by dje04001** [comment]
Folder 636 Loader Issues has  messages for traveler Jacquline Ho.
21478_PNR.txt
22338_PNR.txt
33155_PNR.txt
58444_PNR.txt
And corresponding APIS files will start with the same five-number string

**Comment by donleyac** [comment]
Ok I did some research into this issue. Based on the initial spec I am grouping current itinerary by pnr_ref code and pnr id. As long as the flights share those elements then they would be in current itinerary, otherwise they show up in total flight history.

**Comment by dje04001** [comment]
SELECT DISTINCT * FROM pnr_flight pf JOIN pnr_passenger pp ON pf.pnr_id = pp.pnr_id RIGHT OUTER JOIN flight_passenger fp ON fp.flight_id = pf.flight_id and fp.passenger_id = pp.passenger_id JOIN Flight f ON f.id = fp.flight_id WHERE pf.pnr_id != 1 and fp.passenger_id=1;
