### ISSUE TITLE
Flights Grid not Populating Hit Counts

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#686]
Hit counts are represented for the passenger grid.

Flight Grid:
![uploads/f6de8fbf-8a10-46c4-9bef-89c880beaf82/Screen Shot 2017-10-06 at 12.24.00 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ff6de8fbf-8a10-46c4-9bef-89c880beaf82%2FScreen+Shot+2017-10-06+at+12.24.00+PM.png)

Passenger Grid:
![uploads/59154245-e015-432b-848f-0bc89800b800/Screen Shot 2017-10-06 at 12.25.14 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F59154245-e015-432b-848f-0bc89800b800%2FScreen+Shot+2017-10-06+at+12.25.14+PM.png)

No errors are thrown, basically the frontend gets a 0 for rulehitcount and watchlistcount.
I think when it gets the flight by criteria it pulls the flight model from the Flights Table where the rulehitcount and watchlistcount are 0.
![uploads/d3910c78-80e5-4e4e-8d15-5f1c2559d962/Screen Shot 2017-10-06 at 12.28.23 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fd3910c78-80e5-4e4e-8d15-5f1c2559d962%2FScreen+Shot+2017-10-06+at+12.28.23+PM.png)

However, the actual values are in the hit summary table:
![uploads/2d0b7326-c045-426e-9bfc-4ab094aa6c89/Screen Shot 2017-10-06 at 12.30.12 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F2d0b7326-c045-426e-9bfc-4ab094aa6c89%2FScreen+Shot+2017-10-06+at+12.30.12+PM.png)

**Comment by tjwdev** [comment]
This is due to the scheduler being in control of when flight hit counts get updated, manual run processes skip over that portion. Will edit code to collect counts regardless of manual or automated runs, test, and commit.
