### ISSUE TITLE
Flight History | Front end bug, hidden apis tab after clicking link 

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#699]
It might be useful for the user to have links to the passenger details for the flights listed in the Flight History tab. Right now, it would take several clicks or a query on the passenger to navigate to other Details pages for that passenger.

**Comment by tjwdev** [comment]
Perhaps we can have it so that flight history links to the passenger grid page with that particular flight queried as a result.

**Comment by dje04001** [comment]
prime flights within flight history should have links back to the pertaining pax details page for that flight/pax

**Comment by dje04001** [comment]
I just noticed that clicking the link in flight history to a different Passenger Details view does not include the APIS tab. Navigating to the Passenger Details from different links shows the APIS tab.


![uploads/5957def1-fa7f-4182-b9f4-7448aa3f683e/Untitled.2018-08-29 04_35_58.gif](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F5957def1-fa7f-4182-b9f4-7448aa3f683e%2FUntitled.2018-08-29+04_35_58.gif)

**Comment by gtasautumn** [comment]
This appears to be resolved. Will continue testing to confirm.
