### ISSUE TITLE
PNR Tab Seats displaying by flight number not flight id

### ISSUE THREAD

**Issue by donleyac** [US-CBP/GTAS#705]
Seats in the passenger details page, PNR tab was showing seats for the same flight number, but not necessarily for that flight ID. So if you flew on flight 123 on three occasions, it'll show three seats for that flight.

**Comment by donleyac** [comment]
@dje04001 Actually seats on the pnr tab displays all of the seats ever assigned to each passenger on the pnr. I can change it to show only the seat information for each of those passengers for the specific flight associated with the pax-detail.

**Comment by dje04001** [comment]
I wonder if it was just bad test data then. Maybe the PNR record locator
was the same or something. I'll take a closer look when I have more time.
Here's what I'm seeing.

**Comment by donleyac** [comment]
This is what I'm seeing with the test data you provided. 
![uploads/5d3e5f73-c565-40c1-9349-4e788ec3b52c/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F5d3e5f73-c565-40c1-9349-4e788ec3b52c%2Fimage.png)

**Comment by dje04001** [comment]
Here are better examples. Some of the seats in the UI table aren't on the
PNR, but it looks like the seat numbers from APIS don't match the seat
number from PNR in the database seats table for the flightpax. We probably
don't want to show the APIS seats on the PNR tab. What do you think?

**Comment by donleyac** [comment]
Right now apis seats should be filtered out. This is where we determine what gets populated in the pnr seat information table. 
![uploads/d6a876bb-fa8d-4bd4-a10d-2091fdc59b22/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fd6a876bb-fa8d-4bd4-a10d-2091fdc59b22%2Fimage.png)

Notice the !s.getApis, basically that's a check to verify this seat is not associated with an apis message.
