### ISSUE TITLE
Case Management | odd disposition behavior

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#708]
Setting disposition status for FN/LN/DOB watchlist hit, changes second DOC#/DOCtype WL hit.
![uploads/35559153-1bec-4dec-b395-1ecd42012cbc/Screen Shot 2017-11-28 at 11.54.11 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F35559153-1bec-4dec-b395-1ecd42012cbc%2FScreen+Shot+2017-11-28+at+11.54.11+AM.png)

![uploads/e165a9c5-639c-4314-b514-f39048718cfb/Screen Shot 2017-11-28 at 11.54.08 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fe165a9c5-639c-4314-b514-f39048718cfb%2FScreen+Shot+2017-11-28+at+11.54.08+AM.png)

![uploads/c9bece4f-b84f-4487-ba79-40e800c56ee6/Screen Shot 2017-11-28 at 11.54.03 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fc9bece4f-b84f-4487-ba79-40e800c56ee6%2FScreen+Shot+2017-11-28+at+11.54.03+AM.png)

**Comment by dje04001** [comment]
Also cannot close a case with two WL hits

**Comment by ml-git** [comment]
test this with the latest _commit 1081411_

**Comment by dje04001** [comment]
thank you!
