### ISSUE TITLE
QBRB | Add booking detail flights

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#709]
Current state has Airport Origin and Country. We will need to capture more flight information so that a query can be written to find passengers on a PNR with two or more specific flight legs. i.e. find PNR Passengers where Flight Leg X is LHR>IAD and Flight Leg Y is IAD>IAH.

**Comment by dje04001** [comment]
Adding the data elements from booking detail flights will accomplish this.

**Comment by TeddyTesfaye** [comment]
Completed. Ready for test.

**Comment by dje04001** [comment]
Could not save rule?
![uploads/3ecd0815-9eff-48e0-894c-aa8a1e7a869e/Screen Shot 2018-09-10 at 2.48.03 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F3ecd0815-9eff-48e0-894c-aa8a1e7a869e%2FScreen+Shot+2018-09-10+at+2.48.03+PM.png)

**Comment by dje04001** [comment]
Query results return the correct passenger, but the link to the passenger details tries to go to a passenger details page that will not exist, since it's not really a flight. The link should try to go to the passenger / prime flight combination.
