### ISSUE TITLE
Create JSON message schema

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#710]
Create outbound message schema for updating database for third party integration tools. This message intends to deliver post-parsed data to create, read, update, and delete records in an external database.

the json format should follow the same naming convention (camel case) in the Passenger domain object:

[
  {
    "gtasId": 1,
    "firstName": "MARY LARA A",
    "lastName": "EVENS",
    "middleName": null,
    "dob": "1992-11-11",
    "gender": "F",
    "documents": [{
        "documentNumber": "EM111222",
        "issuanceCountry": "BEL",
        "citizenshipCountry": "BEL"
      }],
      "embarkation": "BOS",
      "debarkation": "LHR",
      "derogId": null
  }
]

**Comment by svempati2006** [comment]
Code completed unit tested and checked in to dev,pl review.The out put is:

Type gov.gtas.model.Pnr {"id":null,"createDate":1512576425592,"raw":null,"hashCode":null,"filePath":null,"status":null,"error":null,"edifactMessage":null,"recordLocator":"ABC293949","carrier":"AA","origin":"IAD","originCountry":null,"dateBooked":1512576425592,"dateReceived":null,"departureDate":1512576425592,"daysBookedBeforeTravel":null,"passengerCount":null,"bagCount":3,"baggageWeight":55.0,"baggageUnit":"KG","total_bag_count":null,"total_bag_weight":0.0,"formOfPayment":"CA",

"flights":[{"id":101,"createdAt":1512576425593,"createdBy":"GTAS","updatedAt":null,"updatedBy":null,"carrier":"AA","flightNumber":"0018","fullFlightNumber":null,"origin":"JFK","originCountry":"USA","destination":"IAD","destinationCountry":"USA","flightDate":null,"etdDate":null,"etaDate":null,"etd":1512576425593,"eta":1512576425593,"direction":"I",

"passengers":[{"id":202,"createdAt":1512576425593,"createdBy":"GTAS","updatedAt":null,"updatedBy":null,"passengerType":"P","flights":[],"apisMessage":[],"pnrs":[],"title":null,"firstName":"TESTER","middleName":null,"lastName":"GTAS","suffix":null,"gender":"F","citizenshipCountry":null,"residencyCountry":null,"dob":1512576425593,"age":null,"numberOfDaysVisaValid":null,"embarkation":null,"debarkation":"IAD","embarkCountry":null,"debarkCountry":null,"deleted":false,"reservationReferenceNumber":null,"totalBagWeight":null,"watchlistCheckTimestamp":null,

"documents":[{"id":202,"documentType":"P","documentNumber":"A1234567","expirationDate":null,"issuanceDate":null,"issuanceCountry":null,"passenger":null,"numberOfDaysValid":null}],"attachments":[],"seatAssignments":[],"bags":[],"flightPaxList":[]}],"passengerCount":0,"ruleHitCount":0,"listHitCount":0,"pnrs":[],"operatingFlight":false,"marketingFlight":false}],"passengers":[],"creditCards":[],"frequentFlyers":[],

"addresses":[{"id":101,"createdAt":1512576425592,"createdBy":null,"updatedAt":null,"updatedBy":null,"line1":"TEST ST","line2":null,"line3":null,"city":null,"state":"VA","country":"USA","postalCode":"20195","pnrs":[],"flightPaxList":[]}],"phones":[],"emails":[],

"agencies":[{"id":100,"createdAt":null,"createdBy":null,"updatedAt":null,"updatedBy":null,"name":"TEST AGENCY","location":"IAD","identifier":null,"country":"USA","phone":"8889994545","city":"ALDIE","type":null,"pnrs":[]}],"codeshares":[],"flightLegs":[],"paymentForms":[],"dwellTimes":[],"reservationCreateDate":null,"tripDuration":null}

**Comment by svempati2006** [comment]
The json conversion and message sending API was completed. The API need to be called from persistence layer when saving the incoming data to the database.The JMS need to be up and running to integrate this piece.Otherwise this will throw exceptions and the loading gets failed.
