### ISSUE TITLE
PNR Bag weight in flight_pax table

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#719]
Two passengers on a PNR with different TBD segments, but records in the table receive the bag weight of the first passenger's bags.

UNB+IATA:1+FI++171016:1327+020A07'
UNH+1+PNRGOV:10:1:IA+F6C2C268'
MSG+:22'
ORG+FI:IAD+30096'
TVL+181017:1650+KEF+IAD+FI+645'
EQN+137'
SRC'
RCI+FI:82FC54:181017:1605'
DAT+700:151017:1650+710:181017:1605'
ORG+DL:IAD+70379193:LON+++A+GB:GBP+D050517'
ADD++702:3899 WANE AVENUE:LONDON:::GB::252629380945'
TIF+ODONOGHUE+JENNIFERMRS:A:1'
FTI+FI:813908:::ELITE'
IFT+4:28::YY+CTCE JENNIFER..ODONOGHUE//GMAIL.COM'
REF+:216151692'
FAR+N+++++MIL24'
SSR+DOCS:HK::DL:::::/P/GBR/727961047//14DEC73/F/07NOV20/ODONOGHUE/JENNIFERMRS/DANIELLE'
TKT+37653037653037:T:1'
MON+B:2888.00:GBP+T:2957.94:GBP'
PTK+NR++150417:1010+DL+006+LON'
TXD++3.10:::AY6+8.50:::YQ+3.40:::YC+4.30:::XY+3.10:::XA+2.80:::XF'
DAT+710:130417:0000'
FOP+CA::300.00'
TIF+BOWYER+RODGERMR:A:2'
FTI+FI:848207:::ELITE'
IFT+4:28::YY+CTCE RODGER.BOWYER//YAHOO.COM'
REF+:916040702'
FAR+N+++++MIL24'
SSR+DOCS:HK::DL:::::/P//589567883//12DEC70/M/28DEC18/BOWYER/RODGERMR/GUS'
TKT+21364021364021:T:1'
MON+B:2888.00:GBP+T:2957.94:GBP'
PTK+NR++150417:1010+DL+006+LON'
TXD++3.10:::AY6+8.50:::YQ+3.40:::YC+4.30:::XY+3.10:::XA+2.80:::XF'
DAT+710:130417:0000'
FOP+CC::300.00:MA:XXXXXXXXXXXX3535:0917'
TVL+181017:1650::1910+KEF+IAD+FI+645:B'
APD+777'
SSR+SEAT:HK:2:FI:::KEF:IAD+28B::1+8H::2'
RCI+FI:82FC54'
DAT+2:181017:1450'
TRI++1:::1'
TIF+ODONOGHUE+JENNIFERMRS:A:1'
SSD+28B++++Y'
TBD++01:62:701+++FI:0001::IAD:006'
TRI++2:::2'
TIF+BOWYER+RODGERMR:A:2'
SSD+8H++++Y'
TBD++01:57:701+++FI:0002::IAD:006'
ABI+1+:LHRRR+LON++DL'
DAT+ZT:071210:1010'
UNT+5764'
UNZ+1+020A07'

**Comment by svempati2006** [comment]
Code completed unit tested and checked into Dev branch. Pl review.
