### ISSUE TITLE
Pax Details aren't displaying for enhanced manifest data

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#733]

**Comment by dje04001** [comment]
uploading the same message, but changing the flight date results in Pax details that look like this

![uploads/9fc0c2f8-b39a-4941-a1d7-aa8052397077/Screen Shot 2017-12-17 at 4.20.37 AM.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F9fc0c2f8-b39a-4941-a1d7-aa8052397077%2FScreen+Shot+2017-12-17+at+4.20.37+AM.jpg)

**Comment by svempati2006** [comment]
Code completed unit tested and checked into Dev branch.Pl review.
