### ISSUE TITLE
TBD | Bag-related bug

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#743]
Bag IDs are incorrect. Partially a data quality issue, but it doesn't appear to be parsing/loading
correctly.

UNB+IATA:1+ET++180122:0055+12345678905'
UNH+1+PNRGOV:10:1:IA+123456789'
MSG+:22'
ORG+ET:ADD+59154'
TVL+250118:0355+EBB+ADD+ET+337'
EQN+55'
SRC'
RCI+ET:A78AC0:251117:0310'
DAT+700:220118:0355+710:251117:0310'
ORG+DL:IAD+70379193:LON+++A+GB:GBP+D050517'
ADD++702:6770 NEWELL AVENUE:OSAKA:::JP::574182328197'
TIF+GRILL+COLINMR:A:1'
FTI+ET:359495:::ELITE'
IFT+4:28::YY+CTCE COLIN.GRILL//YAHOO.COM'
REF+:534338051'
FAR+N+++++MIL24'
SSR+DOCS:HK::DL:::::/P/USA/186246962//22FEB80/M/11SEP24/GRILL/COLINMR/PATRICK'
TKT+37645037645037:T:1'
MON+B:2888.00:GBP+T:2957.94:GBP'
PTK+NR++150417:1010+DL+006+LON'
TXD++3.10:::AY6+8.50:::YQ+3.40:::YC+4.30:::XY+3.10:::XA+2.80:::XF'
DAT+710:130417:0000'
IFT+4:43+COLIN GRILL+STREET ADDRESS CITY STATE ZIP CODE+PHONE NUMBER'
TIF+REEVES+TANISHAMRS:A:2'
FTI+ET:512797:::ELITE'
IFT+4:28::YY+CTCE TANISHA..REEVES//GMAIL.COM'
REF+:903003968'
FAR+N+++++MIL24'
SSR+DOCS:HK::DL:::::/P/USA/688312530//12AUG83/F/26APR23/REEVES/TANISHAMRS/BERNADETTE'
TKT+53918053918053:T:1'
MON+B:2888.00:GBP+T:2957.94:GBP'
PTK+NR++150417:1010+DL+006+LON'
TXD++3.10:::AY6+8.50:::YQ+3.40:::YC+4.30:::XY+3.10:::XA+2.80:::XF'
DAT+710:130417:0000'
IFT+4:43+TANISHA REEVES+STREET ADDRESS CITY STATE ZIP CODE+PHONE NUMBER'
TIF+SHEDD+ARLINDAMRS:A:3'
FTI+ET:548250:::ELITE'
IFT+4:28::YY+CTCE ARLINDA..SHEDD//GMAIL.COM'
REF+:143733112'
FAR+N+++++MIL24'
SSR+DOCS:HK::DL:::::/P/USA/206896977//22JAN54/F/15SEP25/SHEDD/ARLINDAMRS/ELOUISE'
TKT+37315037315037:T:1'
MON+B:2888.00:GBP+T:2957.94:GBP'
PTK+NR++150417:1010+DL+006+LON'
TXD++3.10:::AY6+8.50:::YQ+3.40:::YC+4.30:::XY+3.10:::XA+2.80:::XF'
DAT+710:130417:0000'
IFT+4:43+ARLINDA SHEDD+STREET ADDRESS CITY STATE ZIP CODE+PHONE NUMBER'
TVL+250118:0355::0555+EBB+ADD+ET+337:B'
APD+777'
SSR+SEAT:HK:3:ET:::EBB:ADD+10H::1+24J::2+2K::3'
RCI+ET:A78AC0'
DAT+2:250118:0155'
TRI++45:::45'
TIF+GRILL+COLINMR:A:1'
SSD+10H++++Y'
TBD++02:79:701+++ET:0066::ADD:006+ET:0067::ADD:006'
TRI++46:::46'
TIF+REEVES+TANISHAMRS:A:2'
SSD+24J++++Y'
TBD++02:79:701+++ET:0067::ADD:006+ET:0068::ADD:006'
TRI++47:::47'
TIF+SHEDD+ARLINDAMRS:A:3'
SSD+2K++++Y'
TBD++02:123:701+++ET:0069::ADD:006+ET:0070::ADD:006'
ABI+1+:LHRRR+LON++DL'
DAT+ZT:071210:1010'
UNT+2266'
UNZ+1+12345678905'

**Comment by dje04001** [comment]
![uploads/26ba7ad9-9883-4a3d-a59c-b2faaeb667bd/Screen Shot 2018-01-23 at 3.06.12 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F26ba7ad9-9883-4a3d-a59c-b2faaeb667bd%2FScreen+Shot+2018-01-23+at+3.06.12+PM.png)

![uploads/01502e55-0143-4d7f-943d-c65f62b6fd76/Screen Shot 2018-01-23 at 3.06.14 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F01502e55-0143-4d7f-943d-c65f62b6fd76%2FScreen+Shot+2018-01-23+at+3.06.14+PM.png)

![uploads/6f8796a5-b56b-4c2e-a6f3-76e2ecc6c51e/Screen Shot 2018-01-23 at 3.05.47 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F6f8796a5-b56b-4c2e-a6f3-76e2ecc6c51e%2FScreen+Shot+2018-01-23+at+3.05.47+PM.png)

**Comment by svempati2006** [comment]
Code completed unit tested and checked into Dev.Pl review.
