### ISSUE TITLE
Security | Session Cookie Without Secure Flag

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#760]
GET /gtas/

a known session cookie may have been set without the secure flag.

When creating the cookie in the code, set the secure flag to true.

**Comment by svempati2006** [comment]
The cookie  secure flag will be set to true automatically when the application configured to use HTTPS:
Uncomment and modify the server config file with the below:

 
    <Connector port="8443" protocol="org.apache.coyote.http11.Http11Protocol"
               maxThreads="150" SSLEnabled="true" scheme="https" secure="true"
               clientAuth="false" sslProtocol="TLS" keystoreFile="LOCATION OF \keystore" keystorePass="password of key store"/>

restart the server and use "https://localhost:8443/gtas"

**Comment by svempati2006** [comment]
![secure-true](https://user-images.githubusercontent.com/5758044/39831800-85c974e8-5393-11e8-8af9-52dbfe63c21c.PNG)
