### ISSUE TITLE
Loader tuning

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#768]
jobScheduler.properties

Max number of files = X

**Comment by dje04001** [comment]
not running, commented out, and irrelevant. actual limitation is handled by ActiveMQ. Max is 1024 messages for a prime flight.

**Comment by originalname51** [comment]
loader refactored since this time. I do not think this ticket reflects on current loader.

**Comment by dje04001** [comment]
You're right. This ticket is OBE.
