### ISSUE TITLE
ElasticSearch | multifield Search / Multiple Query Strings

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#770]
ElasticSearch 2.X allows the searching of more than one field with a bool query. We should investigate this for prioritizing / "boosting" a First Name + Last Name search over just a single name

**Comment by dje04001** [comment]
https://www.elastic.co/guide/en/elasticsearch/guide/current/multi-query-strings.html

**Comment by tsegay** [comment]
Current searching implementation has ElasticSearch Multifield Search in place, as described in the link above. To prioritize / "boost" a First Name + Last Name search over just a single name, the default sorting column has been updated to use ElasticSearch special field '_score'.The '_score' field is calculated internally by elastic and represents how well the fields matches the query.
