### ISSUE TITLE
gov.gtas.parsers.exception.ParseException: Expected segment TRI but got TVL

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#796]
Group 7/TRI segment is conditional. It only becomes mandatory when the child segments are included. I might be wrong, but I don't see where this message violates the PNR grammar. Please see spec doc.

UNB+IATA:1+AY++180419:2240+404351058704'
UNH+1+PNRGOV:13:1:IA+123456789'
MSG+:22'
ORG+AY:DJE+55107'
TVL+200418:1740:180421:0850+JFK+HEL+AY+6'
EQN+1'
SRC'
RCI+AY:168DD7:190118:2240'
DAT+700:190418:1633+710:190418:2240'
ORG+DL:IAD+70379193:LON+++A+GB:GBP+D050517'
ADD++702:8594 HARVEY AVENUE:ST. LOUIS:::US::805643743033'
TIF+DIAS+KELLYMRS:A:1'
FTI+AY:124957:::'
IFT+4:28::YY+CTCE KELLY..DIAS//GMAIL.COM'
REF+:126989223'
FAR+N+++++'
SSR+DOCS:HK::DL:::::/P/USA/718281081//17DEC99/F/21MAY19/DIAS/KELLYMRS/CANDACE'
TKT+21611021611021:T:1'
MON+B:377.36:GBP+T:400.00:GBP'
PTK+NR++150417:1010+DL+006+LON'
TXD++2.26:::AY6+3.40:::YQ+4.53:::YC+5.66:::XY+2.26:::XA+4.53:::XF'
DAT+710:190418'
FOP+CA::400.00'

TVL+190418:1740:200418:0850+JFK+HEL+AY+6:B'
APD+777'
SSR+SEAT:HK:1:AY:::JFK:HEL+6B::1'
RCI+AY:168DD7'
DAT+2:190418:1650'
TRI++225:::225'
TIF+DIAS+KELLYMRS:A:1'
SSD+6B++++Y'
TBD++05:51:701+++AY:0321::TLL:006+AY:0322::TLL:006+AY:0323::TLL:006+AY:0324::TLL:006+AY:0325::TLL:006'
TVL+200418:1155::1225+HEL+TLL+AA:AY+8971:B'
TVL+++++109:M'
APD+777'
SSR+SEAT:HK:1:AY:::HEL:TLL++XXX::1'
RCI+AY:168DD7'
DAT+2:190418:1650'

TVL+240418:1250::1320+TLL+HEL+AA:AY+8977:B'
TVL+++++110:M'
APD+777'
SSR+SEAT:HK:1:AY:::TLL:HEL++XXX::1'
RCI+AY:168DD7'
DAT+2:'
TRI++225:::225'
TIF+DIAS+KELLYMRS:A:1'
SSD+XXX++++Y'
TVL+240418:1405::1510+HEL+LHR+AA:AY+9005:B'
TVL+++++839:M'
APD+777'
SSR+SEAT:HK:1:AY:::HEL:LHR++XXX::1'
RCI+AY:168DD7'
DAT+2:'
TRI++225:::225'
TIF+DIAS+KELLYMRS:A:1'
SSD+XXX++++Y'
ABI+1+:LHRRR+LON++DL'
UNT+57'
UNZ+1+4043510587'

![uploads/fac1c6c8-094e-402f-904d-45b8de540e35/Screen Shot 2018-04-17 at 12.35.21 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ffac1c6c8-094e-402f-904d-45b8de540e35%2FScreen+Shot+2018-04-17+at+12.35.21+PM.png)

**Comment by svempati2006** [comment]
Code completed unit tested and checked into Dev,Pl review.

**Comment by dje04001** [comment]
Failed in DEV/AWS on this file:

UNB+IATA:1+UA++180430:1120+002084789405'
UNH+1+PNRGOV:13:1:IA+123456789'
MSG+:22'
ORG+UA:DJE+55107'
TVL+030518:1220:1505+FRA+IAD+UA+988'
EQN+1'
SRC'
RCI+UA:7CDA25:040318:2220'
DAT+700:250418:1505+710:300418:1120'
ORG+DL:IAD+70379193:LON+++A+GB:GBP+D050517'
ADD++702:1827 OFLYNN AVENUE:DAMMAN:::SA::776462191000'
TIF+BRITTON+JERMAINEMR:A:1'
FTI+UA:496154:::'
IFT+4:28::YY+CTCE JERMAINE..BRITTON//GMAIL.COM'
REF+:438045658'
FAR+N+++++'
SSR+DOCS:HK::DL:::::/P/USA/75122325//14OCT77/M/24SEP26/BRITTON/JERMAINEMR/BRUNO'
TKT+26660026660026:T:1'
MON+B:94.34:GBP+T:100.00:GBP'
PTK+NR++150417:1010+DL+006+LON'
TXD++0.57:::AY6+0.85:::YQ+1.13:::YC+1.42:::XY+0.57:::XA+1.13:::XF'
DAT+710:250418'
FOP+CC::100.00:AX:370266XXXXX8979:0319'
IFT+4:43+JERMAINE BRITTON+8879 WALKDEN AVENUE HO CHI MINH CITY USA 7R19M+290935226954'
TVL+250418:1720:260418:0720+IAD+FRA+UA+989:B'
APD+777'
SSR+SEAT:HK:1:UA:::IAD:FRA+XXX::1'
RCI+UA:7CDA25'
DAT+2:250418:1549'
TRI++267:::267'
TIF+BRITTON+JERMAINEMR:A:1'
SSD+XXX++++Y'
TBD++05:33:701+++UA:0862::KWI:006+UA:0863::KWI:006+UA:0864::KWI:006+UA:0865::KWI:006+UA:0866::KWI:006'
TVL+260418:1335::2005+FRA+KWI+UA:LH+8749:B'
TVL+++++624:M'
APD+777'
SSR+SEAT:HK:1:LH:::FRA:KWI++XXX::1'
RCI+UA:7CDA25'
DAT+2:250418:1549'
TVL+030518:0150::0700+KWI+FRA+UA:LH+8750:B'
TVL+++++625:M'
APD+777'
SSR+SEAT:HK:1:LH:::KWI:FRA++XXX::1'
RCI+UA:7CDA25'
DAT+2:'
TRI++267:::267'
TIF+BRITTON+JERMAINEMR:A:1'
SSD+XXX++++Y'
TVL+030518:1220::1505+FRA+IAD+UA+988:B'
APD+777'
SSR+SEAT:HK:1:UA:::FRA:IAD++20D::1'
RCI+UA:7CDA25'
DAT+2:'
TRI++267:::267'
TIF+BRITTON+JERMAINEMR:A:1'
SSD+20D++++Y'
ABI+1+:LHRRR+LON++DL'
UNT+57'
UNZ+1+0020847894'

**Comment by svempati2006** [comment]
Loaded fine in my local.Pl re test once the Dev in AWS gets updated with the latest.

**Comment by dje04001** [comment]
test passed with dev update
