### ISSUE TITLE
Parser | expected ... but got ....

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#801]
7 percent of PNR messages fail because of grammar

**UNT but got (something other than the categories below) (12/611, 1.96 percent)**

- 254321
- 255764
- 262664
- 264681
- 265153
- 273388
- 279269
- 281058
- 285359
- 296757
- 298268
- 298811

**UNT but got LT (10/611, 1.64 percent)**

- 256595
- 258615
- 261449
- 268242
- 269317
- 276756
- 281298
- 288225
- 294306
- 295400

**UNT but got L (9/611, 1.47 percent)**

- 256107
- 254977
- 261450
- 263069
- 263539
- 279495
- 287388
- 299598
- 299631

**RCI but got IFT (6/611, 0.98 percent)**

- 255768
- 257170
- 257204
- 280066
- 299190
- 299191

**ORG but got UNT (4/611, 0.65 percent)**

- 256182
- 279694
- 282918
- 287795

**One of's:**
TIF but got TVL
Invalid Passenger
Org but got S C

**Comment by dje04001** [comment]
when you're ready for this one, please let me know and I'll pass on sample data.

**Comment by originalname51** [comment]
Loosening parser to ignore all lines that do not conform to 3 characters and a non alphanumeric character allows 54% of the error messages to parse.
