### ISSUE TITLE
TBD Bag Parsing not from prime flight

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#802]
t-72 hour push is parsing TBD bag related elements from prior flight rather than the prime flight.

**Comment by dje04001** [comment]
test file is in the google drive under github tickets / 802

**Comment by svempati2006** [comment]
Code completed unit tested and checked into Dev branch.Pl review.

**Comment by dje04001** [comment]
Prime flight does not have bag information in this push of the PNR. Data parsed and loaded from booking detail flights rather than prime flight.


![uploads/5493f8fa-536d-4545-9c30-667bf93cbb0f/Screen Shot 2018-06-01 at 12.17.27 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F5493f8fa-536d-4545-9c30-667bf93cbb0f%2FScreen+Shot+2018-06-01+at+12.17.27+PM.png)
