### ISSUE TITLE
AWS Cloud Formation 

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#809]

**Comment by TeddyTesfaye** [comment]
Updated 1:
So far the following have been completed:
1. Deployment Architecture Diagram
2. Network Architecture Diagram
3. Cloudformation for IAM groups, users, roles
4. Cloudformation to create elastic IP
5. Cloudformation to create Security Groups
6. Cloudformation to create Subnets in all Availability Zones
7. Cloudformation to create rote tables and for their association with subnets
8. Cloudformation to create EC2 with all of the above resources ( #1 to #7).
