### ISSUE TITLE
FOP queries | finding all passengers who ever used the FOP, not just the ones with a PNR with that form of payment

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#824]
probably similar to the misplaced bag hits.

**Comment by tjwdev** [comment]
The problem with this particular issue is that at its base level, PNR has FOP. If you search as query builder is designed PNR -> FOP = CA. and click "Passengers" then it will find you every passenger that has a PNR that has AT LEAST (with the new changes) that particular FOP. Unless I am misunderstanding this particular ticket, the only way to halt it from doing that would be to further specify your queries.

**Comment by TeddyTesfaye** [comment]
Fixed. Ready for test
