### ISSUE TITLE
Query Builder | Returns no results on exact Flight Number Query

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#83]
The query builder returns no results on an exact match when the flight number exists

To repeat error:
1. Go to query builder
2. Set Query inputs to FLIGHT | Number | equal | DL0324
3. Click QUERY FLIGHTS

If repeated with "contains" instead of equal, and only put in 0324, the query is successful

It appears to be having trouble with the carrier code

**Comment by copenhafer** [comment]
query expects flight number only, not carrier+flight number.

**Comment by dje04001** [comment]
Might be helpful to add a tool tip or an error message if user enters carrier code. What do you think?
