### ISSUE TITLE
PNR Bag-related table 

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#833]
Leave PNR total baggage calculation as-is

add new front-end table for bag-related information pertaining to the prime flight at passenger details home.

Correct flight-pax table loading of bags. Should only be baggage info from prime flight.

**Comment by originalname51** [comment]
Currently updating in order to show the following information on user bags.

Individual's Bag Count/Weight/Destination

**Comment by originalname51** [comment]
Test Case:
1:
a. Parse PNR messages.
b. Goto flight tab
c. Click on Passenger
d. Click on PNR view
e.  Check baggage. Match against PNR.
f.  Check to see if baggage and PNR match correctly.

2.
a. Parse APIS message
b. Go to flight
c. Go to passenger
d. Click on APIS 
e. Verify functionality is the same.

**Comment by originalname51** [comment]
There is an existing bug from flight-history that is unrelated to these changes.
