### ISSUE TITLE
APIS only mode

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#838]
Need a configuration setting for hiding PNR-related fields from QB/RB for countries only using APIS.

**Comment by geoffbays** [comment]
I added two insert lines into gtas_data.sql to add an Apis only flag and an Apis version row to the app_config table. Upon installation the default value of the flag could be changed to 'TRUE', and an Apis version added. Code does not deal with Apis version yet, just uses a new entities file, entitiesApisOnly.json to load the query and rule building fields if the Apis only flag is set to 'TRUE'. Adding these fields to the admin screen could be another step and ticket.

**Comment by geoffbays** [comment]
Added Apis flag and Apis version capability to the admin screen with subsequent checkin.
