### ISSUE TITLE
Query Builder Error - PNR form of payment + PNR days booked before travel

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#839]
each condition works separately, but cannot be used together.

20:36:33.249 [http-nio-8080-exec-9] INFO  g.g.c.QueryBuilderController - QueryBuilderException: org.hibernate.hql.internal.ast.QuerySyntaxException: Invalid path: 'pnr.daysBookedBeforeTravel' [select distinct p.id, p, f from gov.gtas.model.Passenger p, gov.gtas.model.Flight f left join p.pnrs ppnr left join ppnr.paymentForms pf  where exists(select fp from gov.gtas.model.FlightPassenger fp where p.id = fp.passengerId and f.id = fp.flightId) and pnr.daysBookedBeforeTravel <= ?1 AND (ppnr.id = pf.pnr.id and pf.paymentType = ?2)]

**Comment by dje04001** [comment]
appears to work, but takes an exorbitant amount of time to process similar query.
Days booked before travel = 0
form of payment = cash
~150 pnr files in database
query never finishes

**Comment by TeddyTesfaye** [comment]
I believe that fixing Issue #850, resolved this issue too. I tested it and didn't see any performance issues. I was able to get the correct results

**Comment by TeddyTesfaye** [comment]
Reopened it so that Dave can verify it and closes it
