### ISSUE TITLE
QBRB | Dwell time

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#840]
Nothing about dwell time queries or rules is working properly.

21:00:53.537 [http-nio-8080-exec-8] INFO  gov.gtas.querybuilder.JPQLGenerator - Parsed Query: select distinct p.id, p, f from Passenger p, Flight f join p.pnrs pnr join pnr.dwellTimes dwell where exists(select fp from FlightPassenger fp where p.id = fp.passengerId and f.id = fp.flightId) and dwell.dwellTime BETWEEN ?1 and ?2 and dwell.location = f.destination
21:00:53.538 [http-nio-8080-exec-8] INFO  g.g.q.r.QueryBuilderRepository - Getting all passengers with this query: select distinct p.id, p, f from Passenger p, Flight f join p.pnrs pnr join pnr.dwellTimes dwell where exists(select fp from FlightPassenger fp where p.id = fp.passengerId and f.id = fp.flightId) and dwell.dwellTime BETWEEN ?1 and ?2 and dwell.location = f.destination

I'm not sure why the "and dwell.location =f.destination" is there. The query was to find all dwell times between 4 and 5 hours without an airport specified.

**Comment by TeddyTesfaye** [comment]
Reopened it so that Dave can verify it and closes it
