### ISSUE TITLE
PNR | flight origin

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#849]
it's not the first airport in the TL0. it's the first airport in the TVL5.

**Comment by tsegay** [comment]
This seems to be working as expected. Please test it again. is this related to #841 ?

**Comment by dje04001** [comment]
The pnr table in the database for origin and origin_country are picking up the wrong values. For example the pnr with an id of 1 boarded at WDH in country NAM. There's a folder in the drive for test data used with today's date.

![uploads/d1c6e929-990d-4d64-8a41-0a3f31f46991/Screen Shot 2018-08-15 at 2.24.30 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fd1c6e929-990d-4d64-8a41-0a3f31f46991%2FScreen+Shot+2018-08-15+at+2.24.30+AM.png)

**Comment by lnpeng** [comment]
I compared origin and origin country in the PNR table with the origin airport for the first flight leg in the passenger details view. They are consistent.
