### ISSUE TITLE
Parser | relax the parser to not expect segment "CNT" in PNR messages

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#857]
Right now the parser throws an error if f the footer part of a PNR doesn't follow a rigid structure. Weird things tend to happen at the end of production messages, and we don't do anything with the footer. We should relax this logic to accept the message.

**Comment by originalname51** [comment]
[Pull request 875 has unit test changes that might help development ](https://github.com/US-CBP/GTAS/pull/875/ )

**Comment by originalname51** [comment]
Some messages have L' at the end - allowing for this would allow parsing of messages.

**Comment by originalname51** [comment]
Some messages have no gender or birthyear in the SSR+DOCS portion which causes the message to fail.
