### ISSUE TITLE
Upgrade Angular // Switch to React

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#860]

**Comment by dje04001** [comment]
That is correct. We currently use angular, however it's my understanding
that upgrading to a newer version is comparable to a rewrite. If that's the
case, we'll explore all options.

We're not scheduled to make this decision for a few months. All development
is focused on deployment readiness for two countries November. Thanks for
your interest in our project!

**Comment by djKooks** [comment]
Also, it seems better use `npm` instead of `bower` for package manager, cause it seems have some problem. You could refer [this](https://www.npmjs.com/package/bower).
