### ISSUE TITLE
Booking detail compression running, but not compressing flights

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#866]

**Comment by dje04001** [comment]
my mistake, they were different flights

**Comment by dje04001** [comment]
please disregard last comment. issue is valid. Flight has been condensed in the database for quite some time, however two booking details flights are shown
![uploads/831e0ab3-3765-4b50-8c16-734c88825e89/Screen Shot 2018-08-16 at 4.04.32 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F831e0ab3-3765-4b50-8c16-734c88825e89%2FScreen+Shot+2018-08-16+at+4.04.32+PM.png)

![uploads/312a2da3-7e86-46d4-898a-d1736d0051f6/Screen Shot 2018-08-16 at 4.04.11 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F312a2da3-7e86-46d4-898a-d1736d0051f6%2FScreen+Shot+2018-08-16+at+4.04.11+PM.png)

**Comment by originalname51** [comment]
Refactoring and a few design changes eliminated the need for compression. Marking as closed.
