### ISSUE TITLE
live data test environment

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#871]

**Comment by djKooks** [comment]
Is there no dummy data for test? Also, if there is something like `quickstart guide`, is it possible to share in document?

**Comment by dje04001** [comment]
We have plenty of test data, but there's really no substitute for a live
data feed. We're going to simulate a production environment as best we can
to prepare of upcoming deployments.

If you're interested in a data generator, or would like chat off the GitHub
board, please send a request through form on our https://us-cbp.github.io/
GTAS/ page and I'll email you back. Thank you!

**Comment by djKooks** [comment]
@dje04001 thanks!
Also, is there a guide to build project with source code for test(or maybe docker)?

**Comment by djKooks** [comment]
@dje04001 okay, my email is inylove82@gmail.com. If it is okay, just send rough guide for build when you have time. Maybe I could try and update in README about process if is allowed.

Thanks.
