### ISSUE TITLE
Parsing & Loading | Booking date appears to be wrong

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#873]
The date we're parsing and loading for booking date appears to be off. I think it should come from the RCI line. Per the spec doc,

RCI+TZ:W9TEND::230513:181348' | Airline locator W9TEND, created 23 May 2013 at 18:13Z

We're pulling this date from somewhere else, likely the time from the last update.

**Comment by originalname51** [comment]
When processing message from the [spec](https://www.iata.org/iata/passenger-data-toolkit/assets/doc_library/04-pnr/PNRGOV%20EDIFACT%20Implementation%20Guide%2013_1.pdf) it appears what is expected to be the booking date is getting parsed as the reservation date, see line 114 PnrGovParser.

See [pr](https://github.com/US-CBP/GTAS/pull/875)
