### ISSUE TITLE
Error Creating FK On Initial Database Schema Export

### ISSUE THREAD

**Issue by originalname51** [US-CBP/GTAS#874]
When following the install.md there is appears to be an issue in the Case.java class. 

This can be reproduced by following the install instructions, specifically the command, 

mvn hibernate4:export

https://github.com/US-CBP/GTAS/blob/master/INSTALL.md

Flight is mapped from case as
    @ManyToOne(optional=true, fetch = FetchType.EAGER)
    @JoinColumn(name = "flightId",insertable=false, updatable=false, referencedColumnName = "id")

FlightId is defined as
    @Column(name = "flightId", nullable = false)
    private Long flightId;

id is defined as
    @Id  
    @GeneratedValue(strategy = GenerationType.AUTO)  
    @Basic(optional = false)  
    @Column(name = "id", nullable = false, columnDefinition = "bigint unsigned")  
    protected Long id;  
  

This creates an exception when hibernate attempts to add the constraint to the table because the data types are different. One is an unsigned big int and the other is signed. 

alter table cases
  add constraint FK_7291oggbt67tp6gyaks3iqqjv
foreign key (flightId)
references flight (id);

This can be solved on initial database creation by changing the column definition of flightId to "bigint unsigned", and flightId will presumably never be negative.

**Comment by dje04001** [comment]
That's a great catch, thank you. Just out of curiosity, did you pull from the DEV branch, or Master?

**Comment by originalname51** [comment]
I cloned from master. I didn't run it again but it appears Case.java and BaseEntity.java are identical on both master and dev, so I would expect the error on both branches.
