### ISSUE TITLE
Passenger Details | Case history "description" is missing

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#881]
All of the other fields in the table are populating properly, but the description column is not displaying results.

**Comment by dje04001** [comment]
![uploads/0c8705e3-a65b-4d74-8b9b-938c9c667ec5/Screen Shot 2018-09-10 at 4.27.01 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F0c8705e3-a65b-4d74-8b9b-938c9c667ec5%2FScreen+Shot+2018-09-10+at+4.27.01+PM.png)

**Comment by tsegay** [comment]
I think the description column is displaying properly as I have it tested by updating the column from the database. But the comment field (green box below) in the UI, which I think is the description column in the database, is not persisting properly during case creation. 

<img width="1429" alt="screen shot 2018-09-10 at 10 42 56 pm" src="https://user-images.githubusercontent.com/563151/45335216-556aba80-b54c-11e8-8758-1a1952b2f844.png">

-- 

<img width="1422" alt="screen shot 2018-09-10 at 11 01 38 pm" src="https://user-images.githubusercontent.com/563151/45335487-a5964c80-b54d-11e8-827a-d436dda57c86.png">

**Comment by dje04001** [comment]
let's just remove it.
