### ISSUE TITLE
Parser | Update Passenger Generation SSR DOCS

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#884]
Refactor passenger generation for PNRs. Update method to conform to specification, gracefully handle all variations of SSR docs, including getting the best doc.

SSR+DOCS:HK:1:BA:::LAS:LHR:/P/USA/123456789/USA/04JUL76/M/04JUL22/WASHINGTON/GEORGE MAJOR+::2'

Parser didn't catch this document.

**Comment by originalname51** [comment]
Updated SSR parsing to match spec.
