### ISSUE TITLE
Individual Case | FN LN concatenation

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#889]
First name and last name appear to be concatenated... not a high priority

**Comment by originalname51** [comment]
Can not reproduce. Please re-open if this is reproduce-able.

**Comment by dje04001** [comment]
this only appears to happen with quickmatch, and it appears that quickmatch is concatenating names. Refer to the cases table, passengerName is incorrect
![uploads/33830372-1e06-42f3-90d9-a9198e5b7586/Screen Shot 2018-11-19 at 11.09.48 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F33830372-1e06-42f3-90d9-a9198e5b7586%2FScreen+Shot+2018-11-19+at+11.09.48+AM.png)
