### ISSUE TITLE
Fuzzy Watchlist Hit indicator on Flights grid

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#890]
The current state gives no indication to the user for flights that have fuzzy watchlist hits. I'm thinking it might be a good idea to include fuzzy hits in the regular watchlist counter.

**Comment by dje04001** [comment]
and Passengers grid

**Comment by originalname51** [comment]
Creation of rule hits coupled to rule engine. New service will be required to generate new hit details on non-rule engine hits.

**Comment by originalname51** [comment]
Changing sql on passenger query from 
select
        generatedAlias0,
        generatedAlias1,
        generatedAlias2 
    from
        Passenger as generatedAlias0,
        Flight as generatedAlias1,
        FlightPassenger as generatedAlias3 
    left join
        generatedAlias0.hits as generatedAlias2 with generatedAlias2.flight.id=:flightId 
    where
        (
            generatedAlias3.flightId=1L 
        ) 
        and (
            generatedAlias0.id=generatedAlias3.passengerId 
        ) 
        and (
            generatedAlias1.id=1L 
        ) 
    order by
        generatedAlias2.watchListHitCount desc,
        generatedAlias2.ruleHitCount desc,
        generatedAlias1.eta desc
