### ISSUE TITLE
Testing | Groups

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#896]

**Comment by originalname51** [comment]
Groups fail for queries. 

Groups pass for rules

**Comment by originalname51** [comment]
Example of rule for flight legs that utilizes group by

rule "does this work?:admin:0"
date-effective "20-May-2019"
when
$bl1:BookingDetail(origin == "IAD", destination == "FRA")
$bl2:BookingDetail(origin == "FRA", destination == "OSL")
$pnr0:Pnr()
$bl1link:PnrBookingLink(pnrId == $pnr0.id, linkAttributeId == $bl1.id)
$bl2link:PnrBookingLink(pnrId == $pnr0.id, linkAttributeId == $bl2.id)
$p:Passenger()
$plink:PnrPassengerLink(pnrId == $pnr0.id, linkAttributeId == $p.id)
then
resultList.add(new RuleHitDetail(%dL, %dL, "does this work?", $p, null, "BookingDetail Origin is 'IAD'///BookingDetail Destination is 'FRA'///BookingDetail Origin is 'FRA'///BookingDetail Destination is 'OSL'"));
end

**Comment by originalname51** [comment]
Example JPQL that fails when using query:

select distinct p.id, p, p.flight from Passenger p left join p.flight f  join p.bookingDetails bl 

where ((bl.origin = ?1 AND bl.destination = ?2) 
AND (bl.origin = ?3 AND bl.destination = ?4))

**Comment by originalname51** [comment]
Test also included Document number and type.
