### ISSUE TITLE
Audit Log View | Doesn't display most recent disposition change to Aria Stark on 2016-10-25 @ 16:12:28

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#90]

**Comment by jtangGitHub** [comment]
please identify the steps how you get to the bug?

**Comment by dje04001** [comment]
1. navigate to Audit log view (admin/admin/audit log view)
2. Set filter action to: Disposition_Status_Chage
3. Set filter date range to include 2016-10-25
4. Click filter icon to filter
5 .Receive results that do not include disposition status change for Aria Stark*

*This disposition status change exists.
*Set to "Requires Review" by nsamha (2016-10-25 16:23:28 -0400)
*Description = test
