### ISSUE TITLE
can't save rule

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#908]
Can't save rules from the front end

**Comment by dje04001** [comment]
04:33:45.373 [http-nio-8080-exec-7] ERROR gov.gtas.svc.UdrServiceImpl - Error creating udr rule!
gov.gtas.error.CommonServiceException: The JSON UDR specification has a start date in the past.

changed the date and it saves the rule. This is a little concerning, however.

**Comment by geoffbays** [comment]
The fix I put in for this includes a failsafe that sets the rule start date to the current date if somehow the selected start date is earlier than the current date. (which should not happen)
