### ISSUE TITLE
All embarkation rules not firing

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#922]
Passenger Embarkation Airport
Passenger Embarkation Country
Flight_Pax Embarkation Airport
Flight_Pax Embarkation Country

**Comment by dje04001** [comment]
reviewing to see if this was related to timezones

**Comment by originalname51** [comment]
Confirmed, rule made at 11:43pm eastern does not apply until 00:00 the following day.

**Comment by originalname51** [comment]
relates to #908
