### ISSUE TITLE
Travel Frequency | revisit computation

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#963]

**Comment by geoffbays** [comment]
Really should be named Passenger Border Crossings: keep a tally of passenger in and out border crossings for the GTAS host country. Will probably use passenger Id tag to identify passengers over multiple flights. Will probably need to create new database table for the purpose.

**Comment by geoffbays** [comment]
I created a new field in passenger_id_tag, doc_hash_id which is a has of the passenger's document ID, country of issuance and expiration date. This is created during loading. This would be used to track a passenger's history over multiple trips.

**Comment by geoffbays** [comment]
Coded a prototype to put the border crossing data on Redis when new passengers are created in GtasLoaderImpl. Commented out the line that calls it. It does work, but with Redis errors.

**Comment by dje04001** [comment]
maybe we could update the count after the Pentaho ETL job back in the relational database

**Comment by originalname51** [comment]
Now done with neo4j query. We ignore passengers born on Jan 1 as this is a common case for passengers who only have a birth year. Query is below:

WITH duration({days: 30}) AS duration 
MATCH(p:Passenger)-[fl:flew_on]->(f:Flight) 
WHERE date(f.etd_date)>date(date()-duration) 
AND NOT date(p.dob)=date.truncate('year',date(p.dob))
WITH p,count(fl)as flight_count 
WHERE flight_count >= 5
RETURN p.id_tag
