### ISSUE TITLE
Intra-Flight Entity Resolution 

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#978]
using reservation system provided unique IDs to resolve passengers within a "family" of PNR messages.

**Comment by originalname51** [comment]
@tjwdev has worked on and potentially has code already implemented. If picking up this ticket talk to @tjwdev first.

**Comment by dje04001** [comment]
It's time to revive this...

**Comment by originalname51** [comment]
Validated; tested modifying files with the same passenger at different points; did not create mulitple passengers. Tested with different doc # and passenger birthday - resolved to same passenger.
