### ISSUE TITLE
Case Management | Office Role and enhanced feedback loop

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#986]
1. Restrict role to viewing only One Day Lookouts, and limited cases view
2. Limited cases view that hides screener comments
3. Create new rich text screener comments section
3. Relocate "validity" button below officer comments section
4. Change validity button selection to "released", "referred", "missed"
5. If missed is selected, displayed a required comment section
6. Create referral agency table for options

**Comment by originalname51** [comment]
Question 1: Do officers and screeners share the same case
Question 2: Do we want to make a new one day screen instead of use cases.
Question 3: Are officers able to see hits?

**Comment by originalname51** [comment]
The ability to see hits on a case is going to be role based now.

On the case view there will be a different section where comments are displayed for agents / screeners.
